/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Core.Base
public import Mathlib.Algebra.Lie.OfAssociative
public import Mathlib.Algebra.Lie.Subalgebra

/-!
# The dynamical Lie algebra

The **dynamical Lie algebra** (DLA) of a parameterized quantum circuit with
generators `{H₁, …, H_K}` is the Lie closure `g = ⟨i H₁, …, i H_K⟩_Lie` — the
smallest Lie subalgebra (under the matrix commutator `⁅A, B⁆ = A B − B A`)
containing the (skew-Hermitian) generators. Its dimension governs circuit
expressibility, overparametrization, and barren-plateau trainability.

Here the ambient Lie algebra is `gl(N, ℂ) = Matrix (Fin N) (Fin N) ℂ` with its
commutator bracket (`LieAlgebra.ofAssociativeAlgebra`). The DLA is defined for an
arbitrary set of matrix generators via `LieSubalgebra.lieSpan`; the physical
generators `i • Hₖ` are skew-Hermitian, so the resulting algebra lies inside
`u(N)`.

Sources: [RBS+23, Arxiv_Final.tex:636-638] (DLA defined as the Lie closure
`g = ⟨i𝒢⟩_Lie` of the circuit generators); [ASY+24, Quantum-main.tex:58]
(DLAs of parameterized circuits as expressiveness/trainability invariants).

## Main definitions / results

- `QuantumAlg.dynamicalLieAlgebra` — the Lie subalgebra generated by the
  generator set (the Lie closure).
- `QuantumAlg.generators_subset_dynamicalLieAlgebra` — the generators lie in it.
- `QuantumAlg.dynamicalLieAlgebra_le_iff` / `dynamicalLieAlgebra_minimal` — its
  universal property: it is the smallest Lie subalgebra containing the generators.
-/

@[expose] public section

namespace QuantumAlg

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {N : ℕ}

/-- The dynamical Lie algebra generated by a set of matrix generators: the
smallest Lie subalgebra of `gl(N, ℂ)` (with the commutator bracket) containing
them — the Lie closure under nested commutators. -/
def dynamicalLieAlgebra (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ) :=
  LieSubalgebra.lieSpan ℂ (Matrix (Fin N) (Fin N) ℂ) gens

/-- The generators belong to their dynamical Lie algebra. -/
theorem generators_subset_dynamicalLieAlgebra
    (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.subset_lieSpan

/-- **Universal property.** The dynamical Lie algebra is contained in a Lie
subalgebra `K` exactly when all generators are. -/
theorem dynamicalLieAlgebra_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.lieSpan_le

/-- **Minimality.** The dynamical Lie algebra is the smallest Lie subalgebra
containing the generators. -/
theorem dynamicalLieAlgebra_minimal (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  LieSubalgebra.lieSpan_le.mpr h

namespace DynamicalLieAlgebra

/-- Main theorem: the DLA is the smallest Lie subalgebra containing the generators. -/
theorem main (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  dynamicalLieAlgebra_minimal gens h

/-- Public supporting theorem: generators belong to their DLA. -/
theorem main_generators_subset (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  generators_subset_dynamicalLieAlgebra gens

/-- Public supporting theorem: the universal property of the DLA. -/
theorem main_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  dynamicalLieAlgebra_le_iff gens K

end DynamicalLieAlgebra

end

end QuantumAlg
