/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Util.QuantumFisher

/-!
# Local bridge vocabulary for the QFIM / Fubini--Study identification

`QuantumAlg.Util.QuantumFisher` defines and proves the generator-covariance
form of the quantum Fisher information matrix.  The analytic identification
with the second-order Fubini--Study/fidelity expansion is a separate bridge:
it requires choices about the state curve, phase convention, and second-order
calculus.

This module keeps that bridge explicit.  It provides small finite-dimensional
raw-vector facts that are local to the existing covariance-form API, and a
named data structure for contexts that supply the analytic bridge.  The
structure is ordinary data, not a global axiom: downstream statements must
receive an instance/hypothesis of the bridge before using the analytic
identification.
-/

@[expose] public section

namespace QuantumAlg

open Matrix

variable {n : Type*} [Fintype n] {M : ℕ}

/-- Raw Hilbert-space overlap `⟨ψ, φ⟩`, with the same dot-product convention as
`expval`. -/
def stateOverlap (ψ φ : n → ℂ) : ℂ := star ψ ⬝ᵥ φ

theorem stateOverlap_def (ψ φ : n → ℂ) : stateOverlap ψ φ = star ψ ⬝ᵥ φ := rfl

/-- Squared pure-state fidelity, at the raw-vector level. -/
def pureFidelitySq (ψ φ : n → ℂ) : ℝ := Complex.normSq (stateOverlap ψ φ)

theorem pureFidelitySq_self_of_unit {ψ : n → ℂ} (hψ : stateOverlap ψ ψ = 1) :
    pureFidelitySq ψ ψ = 1 := by
  simp [pureFidelitySq, hψ]

/-- Overlap is affine in the second argument. -/
theorem stateOverlap_add_smul (ψ φ v : n → ℂ) (c : ℂ) :
    stateOverlap ψ (φ + c • v) = stateOverlap ψ φ + c * stateOverlap ψ v := by
  simp [stateOverlap, dotProduct_add, dotProduct_smul, smul_eq_mul]

/-- The tangent vector generated by a Hermitian operator under the convention
`∂ψ = -i Aψ`. -/
def generatorTangent (ψ : n → ℂ) (A : Matrix n n ℂ) : n → ℂ :=
  (-Complex.I) • (A *ᵥ ψ)

/-- The projective part of a tangent vector: remove the component parallel to
the state vector.  For a unit state this is the usual raw-vector representative
of the Fubini--Study tangent direction. -/
def projectiveTangent (ψ v : n → ℂ) : n → ℂ :=
  v - stateOverlap ψ v • ψ

/-- The generator tangent has overlap `-i⟨A⟩` with the state. -/
theorem stateOverlap_generatorTangent (ψ : n → ℂ) (A : Matrix n n ℂ) :
    stateOverlap ψ (generatorTangent ψ A) = (-Complex.I) * expval ψ A := by
  simp [stateOverlap, generatorTangent, expval_def, dotProduct_smul, smul_eq_mul]

/-- Projecting out the parallel component of the generator tangent is exactly
`-i` times the centered generator action. -/
theorem generatorTangent_projected_eq (ψ : n → ℂ) (A : Matrix n n ℂ) :
    projectiveTangent ψ (generatorTangent ψ A) = (-Complex.I) • centered ψ A := by
  rw [projectiveTangent, stateOverlap_generatorTangent, generatorTangent, centered]
  ext i
  simp [sub_eq_add_neg, mul_assoc]
  ring

/-- A named, explicit bridge assumption identifying an analytic
Fubini--Study/fidelity second-order metric with the covariance-form QFIM.

This is deliberately data, not an axiom.  Code that needs the analytic
identification must accept such a bridge as a hypothesis, while the core
covariance-form QFIM theorems remain unconditional. -/
structure QFIMFubiniStudyBridge (ψ : n → ℂ) (h : Fin M → Matrix n n ℂ) where
  /-- The analytic metric produced by the Fubini--Study/fidelity second-order
  expansion for the chosen parameterized state curve. -/
  fsMetric : Matrix (Fin M) (Fin M) ℝ
  /-- The supplied proof/assumption that the analytic metric agrees with the
  generator-covariance QFIM used in this library. -/
  fsMetric_eq_qfim : fsMetric = qfim ψ h

theorem QFIMFubiniStudyBridge.metric_eq_qfim {ψ : n → ℂ}
    {h : Fin M → Matrix n n ℂ} (bridge : QFIMFubiniStudyBridge ψ h) :
    bridge.fsMetric = qfim ψ h :=
  bridge.fsMetric_eq_qfim

/-- Symmetry transfers from the covariance-form QFIM to a supplied analytic
Fubini--Study metric bridge. -/
theorem QFIMFubiniStudyBridge.fsMetric_isSymm {ψ : n → ℂ}
    {h : Fin M → Matrix n n ℂ} (bridge : QFIMFubiniStudyBridge ψ h)
    (hh : ∀ a, (h a)ᴴ = h a) :
    bridge.fsMetric.IsSymm := by
  rw [bridge.fsMetric_eq_qfim]
  exact qfim_isSymm hh

/-- Positive semidefiniteness transfers from the covariance-form QFIM to a
supplied analytic Fubini--Study metric bridge. -/
theorem QFIMFubiniStudyBridge.fsMetric_posSemidef {ψ : n → ℂ}
    {h : Fin M → Matrix n n ℂ} (bridge : QFIMFubiniStudyBridge ψ h)
    (hψ : stateOverlap ψ ψ = 1) (hh : ∀ a, (h a)ᴴ = h a) :
    bridge.fsMetric.PosSemidef := by
  rw [bridge.fsMetric_eq_qfim]
  exact qfim_posSemidef hψ hh

end QuantumAlg
