/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Util.Nat
public import Mathlib.Analysis.Real.Sqrt
public import Mathlib.Data.ZMod.Basic
public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.Tactic

/-!
# Finite cyclic discrete-logarithm scope

This module records the source-backed discrete-logarithm problem boundary that later
finite-cyclic algorithms use.  The source-level obligation is an explicit generator,
a target element, and evidence that the target lies in the subgroup generated by the
chosen generator.  The reusable Lean abstraction strengthens this to a generator
covering every element of the ambient group.

The source scope matches Shor's two-register discrete-logarithm algorithm and
the Abelian-HSP discrete-logarithm reduction [Sho95, source.tex:1704-1784]
[dW19, qcnotes.tex:2475-2571].
-/

@[expose] public section

namespace QuantumAlg
namespace FiniteCyclicDLP

variable {G : Type*} [Group G]

/-- A discrete-logarithm instance directly matching the source-level cyclic setting:
an explicit generator, a target element, and a witness that the target is generated by it. -/
structure SourceScope (G : Type*) [Group G] where
  /-- The selected group generator or subgroup generator. -/
  generator : G
  /-- The element whose logarithm is to be recovered. -/
  target : G
  /-- Source-backed obligation: the target lies in the cyclic subgroup generated by `generator`. -/
  target_mem_zpowers : target ∈ Subgroup.zpowers generator

/-- The reusable finite-cyclic abstraction: the same generator is available for every target
in the ambient group. -/
structure LeanAbstraction (G : Type*) [Group G] where
  /-- The chosen generator for the ambient cyclic group. -/
  generator : G
  /-- Every target used by the abstraction is generated by `generator`. -/
  covers : ∀ target : G, target ∈ Subgroup.zpowers generator

/-- A source-scoped DLP instance together with the known finite order of the chosen generator. -/
structure KnownOrderProblem (G : Type*) [Group G] extends SourceScope G where
  /-- The known order used to size the two exponent registers. -/
  order : ℕ
  /-- The declared order is the group-theoretic order of the chosen generator. -/
  order_eq_orderOf : order = orderOf generator
  /-- The known order is finite and nonzero. -/
  order_ne_zero : order ≠ 0

/-- Unbounded exponent registers for the source-level oracle action. -/
structure OracleRegister (G : Type*) [Group G] where
  /-- The exponent `a` in the source-level oracle formula. -/
  leftExponent : ℕ
  /-- The exponent `b` in the source-level oracle formula. -/
  rightExponent : ℕ
  /-- The group workspace `y`. -/
  workspace : G

/-- Bounded exponent registers sized by the known order of the DLP generator. -/
structure BoundedOracleRegister (P : KnownOrderProblem G) where
  /-- The exponent `a`, represented modulo the known order. -/
  leftExponent : Fin P.order
  /-- The exponent `b`, represented modulo the known order. -/
  rightExponent : Fin P.order
  /-- The group workspace `y`. -/
  workspace : G
deriving DecidableEq

/-- A two-register Fourier sample for the finite-cyclic DLP reduction. -/
structure FourierSample (P : KnownOrderProblem G) where
  /-- Frequency observed in the first exponent register. -/
  leftFrequency : ZMod P.order
  /-- Frequency observed in the second exponent register. -/
  rightFrequency : ZMod P.order

/-- A Fourier sample whose left frequency is explicitly invertible, the case in which
classical post-processing recovers the discrete logarithm directly. -/
structure RecoverableFourierSample (P : KnownOrderProblem G) extends FourierSample P where
  /-- A concrete inverse for the first-register frequency. -/
  leftInverse : ZMod P.order
  /-- The inverse witness used by the classical recovery step. -/
  left_mul_inverse : leftFrequency * leftInverse = 1

/-- A point in the two exponent registers, represented modulo the known order. -/
structure TwoRegisterPoint (P : KnownOrderProblem G) where
  /-- First exponent-register coordinate. -/
  left : ZMod P.order
  /-- Second exponent-register coordinate. -/
  right : ZMod P.order

namespace SourceScope

/-- Natural-number scalar candidates used by order-finding and DLP reductions. -/
abbrev Scalar := ℕ

/-- A candidate scalar solves the source-scoped discrete-logarithm instance when its
power of the generator is the target. -/
def CandidateScalar (P : SourceScope G) (x : Scalar) : Prop :=
  P.generator ^ x = P.target

/-- A concrete candidate scalar gives the required source-scope membership witness. -/
private theorem target_mem_zpowers_of_candidate (P : SourceScope G) {x : Scalar}
    (hx : P.CandidateScalar x) : P.target ∈ Subgroup.zpowers P.generator := by
  unfold CandidateScalar at hx
  rw [← hx]
  exact Subgroup.npow_mem_zpowers P.generator x

/-- The stored source-scope membership obligation. -/
theorem target_mem_zpowers' (P : SourceScope G) :
    P.target ∈ Subgroup.zpowers P.generator :=
  P.target_mem_zpowers

/-- The multiplier `g^a x^{-b}` used by the finite-cyclic DLP oracle. -/
def oracleMultiplier (P : SourceScope G) (a b : ℕ) : G :=
  P.generator ^ a * (P.target ^ b)⁻¹

/-- The source-level oracle action
`|a,b,y> ↦ |a,b,y g^a x^{-b}>`, represented as a reversible register map. -/
def oracleAction (P : SourceScope G) (r : OracleRegister G) : OracleRegister G where
  leftExponent := r.leftExponent
  rightExponent := r.rightExponent
  workspace := r.workspace * P.oracleMultiplier r.leftExponent r.rightExponent

/-- Inverse of the source-level oracle action. -/
def oracleInverseAction (P : SourceScope G) (r : OracleRegister G) : OracleRegister G where
  leftExponent := r.leftExponent
  rightExponent := r.rightExponent
  workspace := r.workspace * (P.oracleMultiplier r.leftExponent r.rightExponent)⁻¹

@[simp] theorem oracleAction_leftExponent (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleAction r).leftExponent = r.leftExponent :=
  rfl

@[simp] theorem oracleAction_rightExponent (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleAction r).rightExponent = r.rightExponent :=
  rfl

@[simp] theorem oracleAction_workspace (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleAction r).workspace =
      r.workspace * P.oracleMultiplier r.leftExponent r.rightExponent :=
  rfl

@[simp] theorem oracleInverseAction_leftExponent (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleInverseAction r).leftExponent = r.leftExponent :=
  rfl

@[simp] theorem oracleInverseAction_rightExponent (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleInverseAction r).rightExponent = r.rightExponent :=
  rfl

@[simp] theorem oracleInverseAction_workspace (P : SourceScope G) (r : OracleRegister G) :
    (P.oracleInverseAction r).workspace =
      r.workspace * (P.oracleMultiplier r.leftExponent r.rightExponent)⁻¹ :=
  rfl

@[simp] theorem oracleInverseAction_oracleAction (P : SourceScope G) (r : OracleRegister G) :
    P.oracleInverseAction (P.oracleAction r) = r := by
  cases r
  simp [oracleAction, oracleInverseAction, mul_assoc]

@[simp] theorem oracleAction_oracleInverseAction (P : SourceScope G) (r : OracleRegister G) :
    P.oracleAction (P.oracleInverseAction r) = r := by
  cases r
  simp [oracleAction, oracleInverseAction, mul_assoc]

/-- The source-level oracle is a permutation of the three-register basis. -/
def oracleEquiv (P : SourceScope G) : OracleRegister G ≃ OracleRegister G where
  toFun := P.oracleAction
  invFun := P.oracleInverseAction
  left_inv := P.oracleInverseAction_oracleAction
  right_inv := P.oracleAction_oracleInverseAction

end SourceScope

namespace KnownOrderProblem

/-- The declared known order is positive. -/
theorem order_pos (P : KnownOrderProblem G) : 0 < P.order :=
  Nat.pos_of_ne_zero P.order_ne_zero

/-- The chosen generator has the declared known order. -/
private theorem orderOf_generator (P : KnownOrderProblem G) :
    orderOf P.generator = P.order :=
  P.order_eq_orderOf.symm

/-- Forget the bounded exponent registers to natural-number exponent registers. -/
def BoundedOracleRegister.toOracleRegister {P : KnownOrderProblem G}
    (r : BoundedOracleRegister P) : OracleRegister G where
  leftExponent := r.leftExponent.val
  rightExponent := r.rightExponent.val
  workspace := r.workspace

/-- The known-order oracle action on bounded exponent registers. -/
def oracleAction (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) : BoundedOracleRegister P where
  leftExponent := r.leftExponent
  rightExponent := r.rightExponent
  workspace :=
    r.workspace *
      P.toSourceScope.oracleMultiplier r.leftExponent.val r.rightExponent.val

/-- Inverse of the known-order oracle action on bounded exponent registers. -/
def oracleInverseAction (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) : BoundedOracleRegister P where
  leftExponent := r.leftExponent
  rightExponent := r.rightExponent
  workspace :=
    r.workspace *
      (P.toSourceScope.oracleMultiplier r.leftExponent.val r.rightExponent.val)⁻¹

@[simp] theorem oracleAction_leftExponent (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleAction r).leftExponent = r.leftExponent :=
  rfl

@[simp] theorem oracleAction_rightExponent (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleAction r).rightExponent = r.rightExponent :=
  rfl

@[simp] theorem oracleAction_workspace (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleAction r).workspace =
      r.workspace *
        P.toSourceScope.oracleMultiplier r.leftExponent.val r.rightExponent.val :=
  rfl

@[simp] theorem oracleInverseAction_leftExponent (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleInverseAction r).leftExponent = r.leftExponent :=
  rfl

@[simp] theorem oracleInverseAction_rightExponent (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleInverseAction r).rightExponent = r.rightExponent :=
  rfl

@[simp] theorem oracleInverseAction_workspace (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    (P.oracleInverseAction r).workspace =
      r.workspace *
        (P.toSourceScope.oracleMultiplier r.leftExponent.val r.rightExponent.val)⁻¹ :=
  rfl

@[simp] theorem oracleInverseAction_oracleAction (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    P.oracleInverseAction (P.oracleAction r) = r := by
  cases r
  simp [oracleAction, oracleInverseAction, mul_assoc]

@[simp] theorem oracleAction_oracleInverseAction (P : KnownOrderProblem G)
    (r : BoundedOracleRegister P) :
    P.oracleAction (P.oracleInverseAction r) = r := by
  cases r
  simp [oracleAction, oracleInverseAction, mul_assoc]

/-- The known-order oracle is a permutation of the bounded three-register basis. -/
def oracleEquiv (P : KnownOrderProblem G) :
    BoundedOracleRegister P ≃ BoundedOracleRegister P where
  toFun := P.oracleAction
  invFun := P.oracleInverseAction
  left_inv := P.oracleInverseAction_oracleAction
  right_inv := P.oracleAction_oracleInverseAction

end KnownOrderProblem

namespace TwoRegisterPoint

/-- The exponent value `a-rb` selected by the oracle convention `g^a x^{-b}`. -/
def oracleFiberValue {P : KnownOrderProblem G} (secret : ZMod P.order)
    (p : TwoRegisterPoint P) : ZMod P.order :=
  p.left - secret * p.right

/-- Translate along the hidden line preserving the oracle fiber for secret `r`. -/
def hiddenLineTranslate {P : KnownOrderProblem G} (secret shift : ZMod P.order)
    (p : TwoRegisterPoint P) : TwoRegisterPoint P where
  left := p.left + secret * shift
  right := p.right + shift

@[simp] theorem hiddenLineTranslate_left {P : KnownOrderProblem G}
    (secret shift : ZMod P.order) (p : TwoRegisterPoint P) :
    (p.hiddenLineTranslate secret shift).left = p.left + secret * shift :=
  rfl

@[simp] theorem hiddenLineTranslate_right {P : KnownOrderProblem G}
    (secret shift : ZMod P.order) (p : TwoRegisterPoint P) :
    (p.hiddenLineTranslate secret shift).right = p.right + shift :=
  rfl

/-- Hidden-line translations preserve the oracle fiber `a-rb`. -/
private theorem oracleFiberValue_hiddenLineTranslate {P : KnownOrderProblem G}
    (secret shift : ZMod P.order) (p : TwoRegisterPoint P) :
    (p.hiddenLineTranslate secret shift).oracleFiberValue secret =
      p.oracleFiberValue secret := by
  unfold oracleFiberValue hiddenLineTranslate
  ring

end TwoRegisterPoint

namespace FourierSample

/-- The linear relation carried by a DLP Fourier sample when the hidden scalar is `secret`.
With the oracle convention `g^a x^{-b}` and `x=g^r`, samples lie on
`rightFrequency = -r * leftFrequency`. -/
def LinearRelation {P : KnownOrderProblem G} (S : FourierSample P)
    (secret : ZMod P.order) : Prop :=
  S.rightFrequency = -secret * S.leftFrequency

/-- Equivalent additive-zero form of the DLP Fourier-sample relation. -/
theorem linearRelation_add_eq_zero {P : KnownOrderProblem G} (S : FourierSample P)
    {secret : ZMod P.order} (h : S.LinearRelation secret) :
    secret * S.leftFrequency + S.rightFrequency = 0 := by
  unfold LinearRelation at h
  rw [h]
  ring

/-- Additive-zero form implies the DLP Fourier-sample relation. -/
theorem linearRelation_of_add_eq_zero {P : KnownOrderProblem G} (S : FourierSample P)
    {secret : ZMod P.order}
    (h : secret * S.leftFrequency + S.rightFrequency = 0) :
    S.LinearRelation secret := by
  unfold LinearRelation
  calc
    S.rightFrequency = -(secret * S.leftFrequency) := by
      rw [eq_neg_iff_add_eq_zero]
      simpa [add_comm] using h
    _ = -secret * S.leftFrequency := by
      ring

/-- The DLP Fourier relation is equivalent to the additive-zero form used by
source sampling analyses. -/
private theorem linearRelation_iff_add_eq_zero {P : KnownOrderProblem G}
    (S : FourierSample P) (secret : ZMod P.order) :
    S.LinearRelation secret ↔
      secret * S.leftFrequency + S.rightFrequency = 0 :=
  ⟨S.linearRelation_add_eq_zero, S.linearRelation_of_add_eq_zero⟩

/-- Fourier character exponent attached to a two-register sample. -/
def characterExponent {P : KnownOrderProblem G} (S : FourierSample P)
    (p : TwoRegisterPoint P) : ZMod P.order :=
  S.leftFrequency * p.left + S.rightFrequency * p.right

/-- Samples satisfying the DLP Fourier relation are invariant along the hidden line
preserving the oracle fiber. -/
theorem characterExponent_hiddenLineTranslate_of_linearRelation
    {P : KnownOrderProblem G} (S : FourierSample P) {secret : ZMod P.order}
    (h : S.LinearRelation secret) (shift : ZMod P.order) (p : TwoRegisterPoint P) :
    S.characterExponent (p.hiddenLineTranslate secret shift) =
      S.characterExponent p := by
  unfold LinearRelation at h
  unfold characterExponent TwoRegisterPoint.hiddenLineTranslate
  rw [h]
  ring

/-- Invariance under one hidden-line step forces the DLP Fourier relation. -/
theorem linearRelation_of_characterExponent_hiddenLineStep
    {P : KnownOrderProblem G} (S : FourierSample P) {secret : ZMod P.order}
    (h : ∀ p : TwoRegisterPoint P,
      S.characterExponent (p.hiddenLineTranslate secret 1) =
        S.characterExponent p) :
    S.LinearRelation secret := by
  unfold LinearRelation
  have h0 := h { left := 0, right := 0 }
  unfold characterExponent TwoRegisterPoint.hiddenLineTranslate at h0
  ring_nf at h0
  calc
    S.rightFrequency = -(S.leftFrequency * secret) := by
      rw [eq_neg_iff_add_eq_zero]
      simpa [add_comm] using h0
    _ = -secret * S.leftFrequency := by
      ring

/-- Exact algebraic support criterion for the two-register DLP Fourier relation:
the character exponent is invariant along the hidden line iff the sample satisfies the
linear relation used by classical recovery. -/
theorem linearRelation_iff_characterExponent_hiddenLineStep
    {P : KnownOrderProblem G} (S : FourierSample P) (secret : ZMod P.order) :
    S.LinearRelation secret ↔
      ∀ p : TwoRegisterPoint P,
        S.characterExponent (p.hiddenLineTranslate secret 1) =
          S.characterExponent p := by
  constructor
  · intro h p
    exact S.characterExponent_hiddenLineTranslate_of_linearRelation h 1 p
  · intro h
    exact S.linearRelation_of_characterExponent_hiddenLineStep h

/-- Source/Fourier support predicate for a two-register DLP sample.  The oracle
fibers are hidden-line cosets for the convention `g^a x^{-b}` with `x=g^r`;
after applying the two exponent-register Fourier transforms, support can only
occur on characters invariant under one hidden-line step. -/
def SourceSupport {P : KnownOrderProblem G} (S : FourierSample P)
    (secret : ZMod P.order) : Prop :=
  ∀ p : TwoRegisterPoint P,
    S.characterExponent (p.hiddenLineTranslate secret 1) =
      S.characterExponent p

/-- A source-supported Fourier sample is exactly a sample satisfying the DLP
linear relation used by classical recovery. -/
theorem sourceSupport_iff_linearRelation {P : KnownOrderProblem G}
    (S : FourierSample P) (secret : ZMod P.order) :
    S.SourceSupport secret ↔ S.LinearRelation secret := by
  rw [SourceSupport]
  exact (S.linearRelation_iff_characterExponent_hiddenLineStep secret).symm

/-- Source/Fourier support implies the additive-zero relation consumed by the
finite-cyclic DLP recovery endpoint. -/
theorem add_eq_zero_of_sourceSupport {P : KnownOrderProblem G}
    (S : FourierSample P) {secret : ZMod P.order}
    (h : S.SourceSupport secret) :
    secret * S.leftFrequency + S.rightFrequency = 0 :=
  S.linearRelation_add_eq_zero ((S.sourceSupport_iff_linearRelation secret).mp h)

end FourierSample

namespace RecoverableFourierSample

/-- Upgrade a Fourier sample to a recoverable sample when its left frequency is
provided as a unit. -/
def ofLeftUnit {P : KnownOrderProblem G} (S : FourierSample P)
    (u : (ZMod P.order)ˣ) (hu : S.leftFrequency = u) :
    RecoverableFourierSample P where
  leftFrequency := S.leftFrequency
  rightFrequency := S.rightFrequency
  leftInverse := ↑u⁻¹
  left_mul_inverse := by
    rw [hu]
    exact Units.mul_inv u

/-- Classical recovery from a Fourier sample with invertible first frequency. -/
def recoveredSecret {P : KnownOrderProblem G} (S : RecoverableFourierSample P) : ZMod P.order :=
  -S.rightFrequency * S.leftInverse

/-- The explicit inverse and the Fourier linear relation recover the hidden scalar. -/
theorem recoveredSecret_eq_of_linearRelation {P : KnownOrderProblem G}
    (S : RecoverableFourierSample P) {secret : ZMod P.order}
    (h : S.toFourierSample.LinearRelation secret) :
    S.recoveredSecret = secret := by
  unfold FourierSample.LinearRelation at h
  unfold recoveredSecret
  rw [h]
  calc
    -(-secret * S.leftFrequency) * S.leftInverse = secret * S.leftFrequency * S.leftInverse := by
      ring
    _ = secret * (S.leftFrequency * S.leftInverse) := by
      ring
    _ = secret := by
      rw [S.left_mul_inverse, mul_one]

/-- A recoverable sample satisfying the Fourier linear relation is a complete classical
post-processing certificate for the hidden scalar. -/
structure RecoveryCertificate (P : KnownOrderProblem G) where
  /-- The hidden scalar being recovered. -/
  secret : ZMod P.order
  /-- The observed Fourier sample with an explicit inverse for the left frequency. -/
  sample : RecoverableFourierSample P
  /-- The sample satisfies the DLP Fourier linear relation. -/
  relation : sample.toFourierSample.LinearRelation secret

namespace RecoveryCertificate

/-- Build a complete recovery certificate from a Fourier sample whose left
frequency is supplied as a unit and whose source analysis proves the linear
relation. -/
def ofLeftUnitAndLinearRelation {P : KnownOrderProblem G}
    (secret : ZMod P.order) (S : FourierSample P)
    (u : (ZMod P.order)ˣ) (hu : S.leftFrequency = u)
    (hrelation : S.LinearRelation secret) :
    RecoveryCertificate P where
  secret := secret
  sample := RecoverableFourierSample.ofLeftUnit S u hu
  relation := hrelation

/-- Build a complete recovery certificate from the additive-zero form of the
Fourier relation and a unit witness for the left frequency. -/
def ofLeftUnitAndAddEqZero {P : KnownOrderProblem G}
    (secret : ZMod P.order) (S : FourierSample P)
    (u : (ZMod P.order)ˣ) (hu : S.leftFrequency = u)
    (h : secret * S.leftFrequency + S.rightFrequency = 0) :
    RecoveryCertificate P :=
  ofLeftUnitAndLinearRelation secret S u hu (S.linearRelation_of_add_eq_zero h)

/-- The secret returned by the classical post-processing rule. -/
def output {P : KnownOrderProblem G} (C : RecoveryCertificate P) : ZMod P.order :=
  C.sample.recoveredSecret

/-- Soundness of the classical recovery rule under the stated sampling assumptions. -/
theorem output_eq_secret {P : KnownOrderProblem G} (C : RecoveryCertificate P) :
    C.output = C.secret :=
  C.sample.recoveredSecret_eq_of_linearRelation C.relation

end RecoveryCertificate

end RecoverableFourierSample

namespace Shor

/-! ## Shor source good-output certificates -/

/-- Prime-field discrete-logarithm parameters used in Shor's source analysis.
The finite-cyclic Lean endpoint consumes the order `p - 1`; the power-of-two
Fourier modulus `q` is kept separate because Shor's good-output conditions are
stated before rounding back to the group order [Sho95, source.tex:1704-1784]. -/
structure Parameters where
  /-- Prime-field modulus `p` in Shor's presentation. -/
  primeModulus : ℕ
  /-- Power-of-two Fourier modulus `q`, selected with `p < q < 2p`. -/
  q : ℕ
  /-- Source-side lower comparison `p < q`. -/
  prime_lt_q : primeModulus < q
  /-- Source-side upper comparison `q < 2p`. -/
  q_lt_two_prime : q < 2 * primeModulus
deriving DecidableEq

namespace Parameters

/-- The cyclic group order in Shor's prime-field presentation. -/
def groupOrder (params : Parameters) : ℕ :=
  params.primeModulus - 1

end Parameters

/-- Centered residue `⟨z⟩_q` with Shor's convention
`-q/2 < ⟨z⟩_q ≤ q/2` [Sho95, source.tex:1795-1798]. -/
structure CenteredResidue (params : Parameters) (z : ℤ) where
  /-- The centered representative. -/
  value : ℤ
  /-- Congruence to the original integer modulo `q`. -/
  congruent : ∃ k : ℤ, z = value + k * (params.q : ℤ)
  /-- Strict lower centered-residue bound. -/
  lower : -((params.q : ℤ) / 2) < value
  /-- Upper centered-residue bound. -/
  upper : value ≤ (params.q : ℤ) / 2

/-- Observed source state `|c,d,y⟩` in Shor's discrete-logarithm analysis.
The `yIndex` field records the exponent `k` in `y = g^k`; it is not used by
the deterministic recovery bridge but keeps the source event typed. -/
structure ObservedState (params : Parameters) where
  /-- First Fourier-register observation. -/
  c : Fin params.q
  /-- Second Fourier-register observation. -/
  d : Fin params.q
  /-- Source exponent `k` for the observed group element `y = g^k`. -/
  yIndex : Fin params.groupOrder

namespace ObservedState

/-- Integer whose centered residue is `⟨c(p-1)⟩_q` in Shor's notation. -/
def centeredInput {params : Parameters} (state : ObservedState params) : ℤ :=
  (state.c.val : ℤ) * (params.groupOrder : ℤ)

end ObservedState

/-- The source expression `T = rc+d-r/(p-1)⟨c(p-1)⟩_q` from Shor's
good-output condition [Sho95, source.tex:1790-1808]. -/
noncomputable def T (params : Parameters) (sourceSecret : ℤ)
    (state : ObservedState params)
    (centered : CenteredResidue params state.centeredInput) : ℝ :=
  (sourceSecret : ℝ) * (state.c.val : ℝ) + (state.d.val : ℝ) -
    ((sourceSecret : ℝ) / (params.groupOrder : ℝ)) * (centered.value : ℝ)

/-- Shor's first good-output condition: the centered `T` value is within
`1/2` of an integral multiple of `q` [Sho95, source.tex:1804-1812]. -/
def FirstCondition (params : Parameters) (sourceSecret : ℤ)
    (state : ObservedState params)
    (centered : CenteredResidue params state.centeredInput) : Prop :=
  ∃ j : ℤ, |T params sourceSecret state centered - (j : ℝ) * (params.q : ℝ)| ≤
    (1 : ℝ) / 2

/-- Shor's second good-output condition
`|⟨c(p-1)⟩_q| ≤ q/12` [Sho95, source.tex:1814-1819]. -/
def SecondCondition (params : Parameters)
    (state : ObservedState params)
    (centered : CenteredResidue params state.centeredInput) : Prop :=
  |(centered.value : ℝ)| ≤ (params.q : ℝ) / 12

/-- A source-level good output in Shor's discrete-logarithm analysis. This only
names the two source conditions; the analytic lower-bound proof is supplied by
the probability certificate below. -/
structure GoodOutput (params : Parameters) (sourceSecret : ℤ)
    (state : ObservedState params) where
  /-- Centered residue `⟨c(p-1)⟩_q`. -/
  centered : CenteredResidue params state.centeredInput
  /-- Source condition controlling the first exponential phase. -/
  firstCondition : FirstCondition params sourceSecret state centered
  /-- Source condition controlling the second exponential phase. -/
  secondCondition : SecondCondition params state centered

/-- Shor's postprocessed value
`c' = (c(p-1)-⟨c(p-1)⟩_q)/q` [Sho95, source.tex:1914-1923]. -/
structure CPrime (params : Parameters) (state : ObservedState params)
    (centered : CenteredResidue params state.centeredInput) where
  /-- Natural-number value of the rounded frequency. -/
  value : ℕ
  /-- Defining equation for `c'`. -/
  equation :
    (value : ℤ) * (params.q : ℤ) = state.centeredInput - centered.value

/-- A Shor good output that is recoverable by the direct one-sample Lean
post-processing rule: the postprocessed `c'` is supplied as a unit modulo the
known order, and the rounded second frequency satisfies the DLP linear
relation. Shor's full CRT/multiple-sample handling is represented in the
aggregate probability certificate rather than hidden in this one-sample
bridge [Sho95, source.tex:1923-1985]. -/
structure RecoverableGoodOutput (P : KnownOrderProblem G)
    (params : Parameters) (secret : ZMod P.order) where
  /-- Integer representative of the source discrete logarithm. -/
  sourceSecret : ℤ
  /-- Connection between the source integer and the Lean scalar. -/
  sourceSecret_eq : (sourceSecret : ZMod P.order) = secret
  /-- Observed source state. -/
  state : ObservedState params
  /-- Source good-output certificate for the observed state. -/
  good : GoodOutput params sourceSecret state
  /-- Shor's postprocessed frequency `c'`. -/
  cPrime : CPrime params state good.centered
  /-- Rounded second frequency after the nearest-multiple post-processing. -/
  roundedRightFrequency : ZMod P.order
  /-- Unit witness for `c'`; Shor notes non-units require CRT/multiple-sample
  handling rather than direct division. -/
  leftUnit : (ZMod P.order)ˣ
  /-- The Fourier sample's left frequency is the supplied unit. -/
  leftFrequency_eq_leftUnit : (cPrime.value : ZMod P.order) = leftUnit
  /-- Additive-zero form of the DLP Fourier relation for this recoverable
  postprocessed output. -/
  addEqZero :
    secret * (cPrime.value : ZMod P.order) + roundedRightFrequency = 0

namespace RecoverableGoodOutput

/-- Fourier sample obtained from a recoverable Shor good output. The first
frequency is Shor's postprocessed `c'`, not the raw observed `c`. -/
def toFourierSample {P : KnownOrderProblem G} {params : Parameters}
    {secret : ZMod P.order}
    (output : RecoverableGoodOutput P params secret) : FourierSample P where
  leftFrequency := output.cPrime.value
  rightFrequency := output.roundedRightFrequency

/-- Unit witness for the postprocessed first frequency. -/
theorem toFourierSample_leftFrequency_eq_leftUnit {P : KnownOrderProblem G}
    {params : Parameters} {secret : ZMod P.order}
    (output : RecoverableGoodOutput P params secret) :
    output.toFourierSample.leftFrequency = output.leftUnit := by
  simpa [toFourierSample] using output.leftFrequency_eq_leftUnit

/-- Additive-zero DLP relation for the postprocessed Shor Fourier sample. -/
theorem toFourierSample_addEqZero {P : KnownOrderProblem G}
    {params : Parameters} {secret : ZMod P.order}
    (output : RecoverableGoodOutput P params secret) :
    secret * output.toFourierSample.leftFrequency +
        output.toFourierSample.rightFrequency = 0 := by
  simpa [toFourierSample] using output.addEqZero

end RecoverableGoodOutput

/-- Aggregate source certificate for Shor good outputs over a full sampling
experiment. The fields keep Shor's constants visible: per-good-state
probability `1/(20q^2)`, at least `q/12` good `(c,d)` pairs, and single-run
good-output probability at least `1/480` [Sho95, source.tex:1875-1905]. The
`successNumerator/successDenominator` fields represent the repeated-sampling
and CRT post-processing bound used by the final finite-cyclic DLP endpoint
[Sho95, source.tex:1939-1985]. -/
structure RepeatedGoodOutputMassCertificate (params : Parameters) (Ω : Type*) where
  /-- Probability mass assigned to complete source-level sampling outcomes. -/
  prob : Ω → ℝ
  /-- Source probabilities are nonnegative. -/
  prob_nonneg : ∀ outcome, 0 ≤ prob outcome
  /-- Outcomes for which the repeated Shor post-processing succeeds. -/
  goodEvents : Finset Ω
  /-- Number of source-good `(c,d)` pairs tracked by the certificate. -/
  goodPairCount : ℕ
  /-- Source lower bound: at least `q/12` good pairs. -/
  goodPairCount_lowerBound : params.q / 12 ≤ goodPairCount
  /-- Single-run good-output mass used before repetition/CRT aggregation. -/
  singleRunGoodMass : ℝ
  /-- Source lower bound: a single run has good-output probability at least
  `1/480`. -/
  singleRunGoodMass_lowerBound : (1 : ℝ) / 480 ≤ singleRunGoodMass
  /-- Per-good-state lower-bound constant retained from Shor's analysis. -/
  perGoodStateLowerBound :
    ∀ outcome, outcome ∈ goodEvents →
      (1 : ℝ) / (20 * (params.q : ℝ) ^ 2) ≤ prob outcome
  /-- Number of experiments batched before CRT post-processing. -/
  repeatedExperimentCount : ℕ
  /-- Numerator of the final repeated-sampling success lower bound. -/
  successNumerator : ℕ
  /-- Denominator of the final repeated-sampling success lower bound. -/
  successDenominator : ℕ
  /-- The success denominator is nonzero. -/
  successDenominator_pos : 0 < successDenominator
  /-- Final repeated-sampling success lower bound is at least `2/3`. -/
  success_atLeast_twoThirds :
    2 * successDenominator ≤ 3 * successNumerator
  /-- The final rational lower bound is below the certified good-event mass. -/
  rationalBound_le_goodMass :
    (successNumerator : ℝ) / (successDenominator : ℝ) ≤ goodEvents.sum prob
  /-- The final certified good-event mass is bounded by one. -/
  goodMass_le_one : goodEvents.sum prob ≤ 1

end Shor

/-! ## Classical recovery and sampling certificates -/

/-- A finite-cyclic DLP run certificate: the sampled Fourier relation is strong
enough for classical recovery, and the external sampling analysis supplies the
success lower bound as a rational inequality. -/
structure AlgorithmRunCertificate (P : KnownOrderProblem G) where
  /-- Fourier-sample recovery certificate for the hidden scalar. -/
  recovery : RecoverableFourierSample.RecoveryCertificate P
  /-- Numerator of the certified success probability. -/
  successNumerator : ℕ
  /-- Denominator of the certified success probability. -/
  successDenominator : ℕ
  /-- The success denominator is nonzero. -/
  successDenominator_pos : 0 < successDenominator
  /-- Rational lower bound: `successNumerator / successDenominator ≥ 2/3`. -/
  success_atLeast_twoThirds : 2 * successDenominator ≤ 3 * successNumerator

namespace AlgorithmRunCertificate

/-- Hidden scalar certified by the successful run. -/
def secret {P : KnownOrderProblem G} (run : AlgorithmRunCertificate P) : ZMod P.order :=
  run.recovery.secret

/-- Classical output returned by the recovery rule. -/
def output {P : KnownOrderProblem G} (run : AlgorithmRunCertificate P) : ZMod P.order :=
  run.recovery.output

/-- The run's certified success probability is at least two thirds. -/
def SuccessAtLeastTwoThirds {P : KnownOrderProblem G}
    (run : AlgorithmRunCertificate P) : Prop :=
  2 * run.successDenominator ≤ 3 * run.successNumerator

/-- Correctness of the classical DLP recovery rule for a certified run. -/
theorem output_eq_secret {P : KnownOrderProblem G}
    (run : AlgorithmRunCertificate P) :
    run.output = run.secret :=
  RecoverableFourierSample.RecoveryCertificate.output_eq_secret run.recovery

/-- The stored rational success bound. -/
theorem successAtLeastTwoThirds {P : KnownOrderProblem G}
    (run : AlgorithmRunCertificate P) :
    run.SuccessAtLeastTwoThirds :=
  run.success_atLeast_twoThirds

end AlgorithmRunCertificate

/-- Source-level sampling certificate for the finite-cyclic DLP endpoint. It
separates the Fourier-sampling success analysis from the deterministic recovery
rule: every event in `goodEvents` carries a recovery certificate, and the source
analysis supplies a rational lower bound for the total good-event mass. -/
structure SamplingCertificate (P : KnownOrderProblem G) (Ω : Type*) where
  /-- Probability mass assigned to source-level sampling outcomes. -/
  prob : Ω → ℝ
  /-- Source-level probabilities are nonnegative. -/
  prob_nonneg : ∀ outcome, 0 ≤ prob outcome
  /-- Finite set of outcomes on which the classical recovery rule succeeds. -/
  goodEvents : Finset Ω
  /-- Recovery certificate attached to each good source outcome. -/
  recovery :
    ∀ outcome, outcome ∈ goodEvents →
      RecoverableFourierSample.RecoveryCertificate P
  /-- Numerator of the certified success-probability lower bound. -/
  successNumerator : ℕ
  /-- Denominator of the certified success-probability lower bound. -/
  successDenominator : ℕ
  /-- The success denominator is nonzero. -/
  successDenominator_pos : 0 < successDenominator
  /-- Rational lower bound: `successNumerator / successDenominator ≥ 2/3`. -/
  success_atLeast_twoThirds : 2 * successDenominator ≤ 3 * successNumerator
  /-- The rational lower bound is below the total mass of good outcomes. -/
  rationalBound_le_goodMass :
    (successNumerator : ℝ) / (successDenominator : ℝ) ≤ goodEvents.sum prob
  /-- The certified good-event mass is bounded by one. -/
  goodMass_le_one : goodEvents.sum prob ≤ 1

namespace SamplingCertificate

/-- Build a source sampling certificate from good-event Fourier samples whose
left frequency is a unit and whose additive-zero relation certifies the same
hidden scalar. This constructor leaves the source probability lower-bound proof
as data while deriving every deterministic recovery certificate. -/
def ofLeftUnitAddEqZero {P : KnownOrderProblem G} {Ω : Type*}
    (secret : ZMod P.order)
    (prob : Ω → ℝ)
    (prob_nonneg : ∀ outcome, 0 ≤ prob outcome)
    (goodEvents : Finset Ω)
    (sample :
      ∀ outcome, outcome ∈ goodEvents → FourierSample P)
    (leftUnit :
      ∀ outcome (_ : outcome ∈ goodEvents), (ZMod P.order)ˣ)
    (leftUnit_eq :
      ∀ outcome (hgood : outcome ∈ goodEvents),
        (sample outcome hgood).leftFrequency = leftUnit outcome hgood)
    (addEqZero :
      ∀ outcome (hgood : outcome ∈ goodEvents),
        secret * (sample outcome hgood).leftFrequency +
            (sample outcome hgood).rightFrequency = 0)
    (successNumerator successDenominator : ℕ)
    (successDenominator_pos : 0 < successDenominator)
    (success_atLeast_twoThirds : 2 * successDenominator ≤ 3 * successNumerator)
    (rationalBound_le_goodMass :
      (successNumerator : ℝ) / (successDenominator : ℝ) ≤ goodEvents.sum prob)
    (goodMass_le_one : goodEvents.sum prob ≤ 1) :
    SamplingCertificate P Ω where
  prob := prob
  prob_nonneg := prob_nonneg
  goodEvents := goodEvents
  recovery := fun outcome hgood =>
    RecoverableFourierSample.RecoveryCertificate.ofLeftUnitAndAddEqZero
      secret (sample outcome hgood) (leftUnit outcome hgood)
      (leftUnit_eq outcome hgood) (addEqZero outcome hgood)
  successNumerator := successNumerator
  successDenominator := successDenominator
  successDenominator_pos := successDenominator_pos
  success_atLeast_twoThirds := success_atLeast_twoThirds
  rationalBound_le_goodMass := rationalBound_le_goodMass
  goodMass_le_one := goodMass_le_one

/-- Total probability mass of the certified good-event set. -/
def goodMass {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) : ℝ :=
  sampling.goodEvents.sum sampling.prob

/-- The sampling certificate's stored rational success lower bound is at least
two thirds. -/
def SuccessAtLeastTwoThirds {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) : Prop :=
  2 * sampling.successDenominator ≤ 3 * sampling.successNumerator

/-- Every certified good sampling outcome recovers its hidden scalar. -/
theorem recovery_output_eq_secret {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω)
    (outcome : Ω) (hgood : outcome ∈ sampling.goodEvents) :
    (sampling.recovery outcome hgood).output =
      (sampling.recovery outcome hgood).secret :=
  RecoverableFourierSample.RecoveryCertificate.output_eq_secret
    (sampling.recovery outcome hgood)

/-- The stored rational success bound. -/
theorem successAtLeastTwoThirds {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    sampling.SuccessAtLeastTwoThirds :=
  sampling.success_atLeast_twoThirds

/-- The certified rational lower bound is below the finite good-event mass. -/
theorem rationalBound_le_goodMass' {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    (sampling.successNumerator : ℝ) /
        (sampling.successDenominator : ℝ) ≤ sampling.goodMass :=
  sampling.rationalBound_le_goodMass

/-- The stored rational lower-bound certificate implies the real-number
two-thirds lower bound. -/
theorem twoThirds_le_rationalBound {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    (2 : ℝ) / 3 ≤
      (sampling.successNumerator : ℝ) / (sampling.successDenominator : ℝ) := by
  have hden : (0 : ℝ) < (sampling.successDenominator : ℝ) := by
    exact_mod_cast sampling.successDenominator_pos
  have hcert :
      (2 : ℝ) * (sampling.successDenominator : ℝ) ≤
        3 * (sampling.successNumerator : ℝ) := by
    exact_mod_cast sampling.success_atLeast_twoThirds
  rw [div_le_div_iff₀ (by norm_num : (0 : ℝ) < 3) hden]
  simpa [mul_comm, mul_left_comm, mul_assoc] using hcert

/-- The certified good-event mass is at least two thirds as a real
probability lower bound. -/
theorem twoThirds_le_goodMass {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    (2 : ℝ) / 3 ≤ sampling.goodMass :=
  sampling.twoThirds_le_rationalBound.trans sampling.rationalBound_le_goodMass'

/-- The finite good-event mass is nonnegative. -/
theorem goodMass_nonneg {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    0 ≤ sampling.goodMass := by
  unfold goodMass
  exact Finset.sum_nonneg fun outcome _ => sampling.prob_nonneg outcome

/-- The certified good-event mass is bounded by one. -/
theorem goodMass_le_one' {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω) :
    sampling.goodMass ≤ 1 :=
  sampling.goodMass_le_one

/-- A good source outcome can be viewed as the earlier single-run certificate.
This preserves the deterministic endpoint while making the sampling assumption
explicit at the source-event layer. -/
def toAlgorithmRunCertificate {P : KnownOrderProblem G} {Ω : Type*}
    (sampling : SamplingCertificate P Ω)
    (outcome : Ω) (hgood : outcome ∈ sampling.goodEvents) :
    AlgorithmRunCertificate P where
  recovery := sampling.recovery outcome hgood
  successNumerator := sampling.successNumerator
  successDenominator := sampling.successDenominator
  successDenominator_pos := sampling.successDenominator_pos
  success_atLeast_twoThirds := sampling.success_atLeast_twoThirds

/-- Build the endpoint sampling certificate from Shor source-good-output data.
The deterministic recovery part is derived from each recoverable postprocessed
good output; Shor's analytic probability constants and repeated-sampling/CRT
success bound remain explicit fields of the mass certificate. -/
def ofShorRecoverableGoodOutputs {P : KnownOrderProblem G} {Ω : Type*}
    {params : Shor.Parameters}
    (secret : ZMod P.order)
    (mass : Shor.RepeatedGoodOutputMassCertificate params Ω)
    (output :
      ∀ outcome, outcome ∈ mass.goodEvents →
        Shor.RecoverableGoodOutput P params secret) :
    SamplingCertificate P Ω :=
  SamplingCertificate.ofLeftUnitAddEqZero secret mass.prob mass.prob_nonneg
    mass.goodEvents
    (fun outcome hgood => (output outcome hgood).toFourierSample)
    (fun outcome hgood => (output outcome hgood).leftUnit)
    (fun outcome hgood =>
      (output outcome hgood).toFourierSample_leftFrequency_eq_leftUnit)
    (fun outcome hgood => (output outcome hgood).toFourierSample_addEqZero)
    mass.successNumerator mass.successDenominator mass.successDenominator_pos
    mass.success_atLeast_twoThirds mass.rationalBound_le_goodMass
    mass.goodMass_le_one

end SamplingCertificate

/-! ## Two-register Fourier support certificates -/

/-- Source-level support certificate for the two-register finite-cyclic DLP
Fourier-sampling step.  The probability mass and unit-frequency success remain
source data, while the deterministic Fourier-support relation is expressed as
invariance of the character exponent along the hidden line. -/
structure FourierSamplingSupport (P : KnownOrderProblem G) (Ω : Type*) where
  /-- Hidden scalar to be recovered. -/
  secret : ZMod P.order
  /-- Probability mass assigned to source-level sampling outcomes. -/
  prob : Ω → ℝ
  /-- Source-level probabilities are nonnegative. -/
  prob_nonneg : ∀ outcome, 0 ≤ prob outcome
  /-- Finite set of outcomes on which the source sampling analysis succeeds. -/
  goodEvents : Finset Ω
  /-- Fourier sample attached to each source-good outcome. -/
  sample : ∀ outcome, outcome ∈ goodEvents → FourierSample P
  /-- Unit witness for the first Fourier frequency on each good outcome. -/
  leftUnit : ∀ outcome (_ : outcome ∈ goodEvents), (ZMod P.order)ˣ
  /-- The first Fourier frequency is the supplied unit. -/
  leftUnit_eq :
    ∀ outcome (hgood : outcome ∈ goodEvents),
      (sample outcome hgood).leftFrequency = leftUnit outcome hgood
  /-- Exact Fourier support relation obtained from the two-register QFT analysis. -/
  sourceSupport :
    ∀ outcome (hgood : outcome ∈ goodEvents),
      (sample outcome hgood).SourceSupport secret
  /-- Numerator of the certified success-probability lower bound. -/
  successNumerator : ℕ
  /-- Denominator of the certified success-probability lower bound. -/
  successDenominator : ℕ
  /-- The success denominator is nonzero. -/
  successDenominator_pos : 0 < successDenominator
  /-- Rational lower bound: `successNumerator / successDenominator ≥ 2/3`. -/
  success_atLeast_twoThirds : 2 * successDenominator ≤ 3 * successNumerator
  /-- The rational lower bound is below the total mass of good outcomes. -/
  rationalBound_le_goodMass :
    (successNumerator : ℝ) / (successDenominator : ℝ) ≤ goodEvents.sum prob
  /-- The certified good-event mass is bounded by one. -/
  goodMass_le_one : goodEvents.sum prob ≤ 1

namespace FourierSamplingSupport

/-- The additive-zero DLP relation derived from the two-register Fourier support
predicate on a certified good outcome. -/
theorem addEqZero {P : KnownOrderProblem G} {Ω : Type*}
    (support : FourierSamplingSupport P Ω)
    (outcome : Ω) (hgood : outcome ∈ support.goodEvents) :
    support.secret * (support.sample outcome hgood).leftFrequency +
        (support.sample outcome hgood).rightFrequency = 0 :=
  (support.sample outcome hgood).add_eq_zero_of_sourceSupport
    (support.sourceSupport outcome hgood)

/-- Build a two-register Fourier-support certificate from good-event Fourier
samples whose first frequency is a unit and whose additive-zero relation has
already been proved by the source analysis. This is the converse packaging of
`addEqZero`: the additive-zero form gives the linear relation, and the linear
relation is equivalent to hidden-line character invariance. -/
def ofLeftUnitAddEqZero {P : KnownOrderProblem G} {Ω : Type*}
    (secret : ZMod P.order)
    (prob : Ω → ℝ)
    (prob_nonneg : ∀ outcome, 0 ≤ prob outcome)
    (goodEvents : Finset Ω)
    (sample :
      ∀ outcome, outcome ∈ goodEvents → FourierSample P)
    (leftUnit :
      ∀ outcome (_ : outcome ∈ goodEvents), (ZMod P.order)ˣ)
    (leftUnit_eq :
      ∀ outcome (hgood : outcome ∈ goodEvents),
        (sample outcome hgood).leftFrequency = leftUnit outcome hgood)
    (addEqZero :
      ∀ outcome (hgood : outcome ∈ goodEvents),
        secret * (sample outcome hgood).leftFrequency +
            (sample outcome hgood).rightFrequency = 0)
    (successNumerator successDenominator : ℕ)
    (successDenominator_pos : 0 < successDenominator)
    (success_atLeast_twoThirds : 2 * successDenominator ≤ 3 * successNumerator)
    (rationalBound_le_goodMass :
      (successNumerator : ℝ) / (successDenominator : ℝ) ≤ goodEvents.sum prob)
    (goodMass_le_one : goodEvents.sum prob ≤ 1) :
    FourierSamplingSupport P Ω where
  secret := secret
  prob := prob
  prob_nonneg := prob_nonneg
  goodEvents := goodEvents
  sample := sample
  leftUnit := leftUnit
  leftUnit_eq := leftUnit_eq
  sourceSupport := fun outcome hgood =>
    ((sample outcome hgood).sourceSupport_iff_linearRelation secret).mpr
      ((sample outcome hgood).linearRelation_of_add_eq_zero
        (addEqZero outcome hgood))
  successNumerator := successNumerator
  successDenominator := successDenominator
  successDenominator_pos := successDenominator_pos
  success_atLeast_twoThirds := success_atLeast_twoThirds
  rationalBound_le_goodMass := rationalBound_le_goodMass
  goodMass_le_one := goodMass_le_one

/-- Build a two-register Fourier-support certificate from Shor source-good-output
data. The deterministic support relation is derived from each recoverable
postprocessed output's additive-zero Fourier relation; the probability and
repeated-sampling/CRT success accounting remain explicit source data. -/
def ofShorRecoverableGoodOutputs {P : KnownOrderProblem G} {Ω : Type*}
    {params : Shor.Parameters}
    (secret : ZMod P.order)
    (mass : Shor.RepeatedGoodOutputMassCertificate params Ω)
    (output :
      ∀ outcome, outcome ∈ mass.goodEvents →
        Shor.RecoverableGoodOutput P params secret) :
    FourierSamplingSupport P Ω :=
  FourierSamplingSupport.ofLeftUnitAddEqZero secret mass.prob mass.prob_nonneg
    mass.goodEvents
    (fun outcome hgood => (output outcome hgood).toFourierSample)
    (fun outcome hgood => (output outcome hgood).leftUnit)
    (fun outcome hgood =>
      (output outcome hgood).toFourierSample_leftFrequency_eq_leftUnit)
    (fun outcome hgood => (output outcome hgood).toFourierSample_addEqZero)
    mass.successNumerator mass.successDenominator mass.successDenominator_pos
    mass.success_atLeast_twoThirds mass.rationalBound_le_goodMass
    mass.goodMass_le_one

/-- Convert the source/Fourier support certificate into the generic sampling
certificate consumed by the finite-cyclic DLP endpoint. -/
def toSamplingCertificate {P : KnownOrderProblem G} {Ω : Type*}
    (support : FourierSamplingSupport P Ω) :
    SamplingCertificate P Ω :=
  SamplingCertificate.ofLeftUnitAddEqZero support.secret support.prob
    support.prob_nonneg support.goodEvents support.sample support.leftUnit
    support.leftUnit_eq support.addEqZero support.successNumerator
    support.successDenominator support.successDenominator_pos
    support.success_atLeast_twoThirds support.rationalBound_le_goodMass
    support.goodMass_le_one

@[simp] theorem toSamplingCertificate_goodEvents {P : KnownOrderProblem G}
    {Ω : Type*} (support : FourierSamplingSupport P Ω) :
    support.toSamplingCertificate.goodEvents = support.goodEvents :=
  rfl

@[simp] theorem toSamplingCertificate_goodMass {P : KnownOrderProblem G}
    {Ω : Type*} (support : FourierSamplingSupport P Ω) :
    support.toSamplingCertificate.goodMass =
      support.goodEvents.sum support.prob :=
  rfl

end FourierSamplingSupport

/-! ## Short-DLP post-processing success bounds

The support vocabulary below records the explicit success lower bound,
group-operation bound, and lookup-table bound from Ekera's short-DLP
post-processing theorem [E23, arxiv-v5.tex:1108-1128].
-/

namespace ShortDLPPostprocessing

/-- Source parameters for the Ekera short-DLP post-processing success bound.
The fields mirror the integer side conditions in the source statement: `Delta`
is encoded as `delta`, `ell = m - delta`, `tau` lies in `[0, ell]`, `t` lies
in `[0, m)`, and `c` is a positive integer search/lookup constant [E23,
arxiv-v5.tex:1103-1128]. -/
structure Parameters where
  /-- Short-DLP post-processing window parameter. -/
  m : ℕ
  /-- Short-DLP post-processing approximation tolerance. -/
  delta : ℕ
  /-- Short-DLP post-processing rounding parameter. -/
  tau : ℕ
  /-- Short-DLP post-processing lattice width parameter. -/
  t : ℕ
  /-- Short-DLP post-processing scaling parameter. -/
  c : ℕ
  delta_lt_m : delta < m
  tau_le_ell : tau ≤ m - delta
  t_lt_m : t < m
  c_pos : 0 < c

namespace Parameters

/-- The short-DLP source parameter `ell = m - Delta`. -/
def ell (params : Parameters) : ℕ :=
  params.m - params.delta

/-- The source search-space expression
`N_{Delta,tau,t} = 2^(Delta+tau+1) + 2^(tau+t+2) + 2` [E23,
arxiv-v5.tex:1108-1116]. -/
def searchSpace (params : Parameters) : ℕ :=
  2 ^ (params.delta + params.tau + 1) +
    2 ^ (params.tau + params.t + 2) + 2

/-- First success-probability factor
`max(0, 1 - 2^(-tau) - 2^(-2tau-1) - 2^(-3tau)/6)` [E23,
arxiv-v5.tex:1108-1114]. -/
noncomputable def firstSuccessFactor (params : Parameters) : ℝ :=
  max 0
    (1 - (2 : ℝ) ^ (-(params.tau : ℤ)) -
      (2 : ℝ) ^ (-((2 * params.tau + 1 : ℕ) : ℤ)) -
      ((2 : ℝ) ^ (-((3 * params.tau : ℕ) : ℤ))) / 6)

/-- Second success-probability factor
`max(0, 1 - 2^(Delta - 2(t-1) - tau))`. The exponent is an integer exponent
to avoid silently truncating the source expression [E23,
arxiv-v5.tex:1110-1114]. -/
noncomputable def secondSuccessFactor (params : Parameters) : ℝ :=
  max 0
    (1 - (2 : ℝ) ^
      ((params.delta : ℤ) - 2 * ((params.t : ℤ) - 1) - (params.tau : ℤ)))

/-- Source lower bound for the short-DLP post-processing success probability
[E23, arxiv-v5.tex:1108-1114]. -/
noncomputable def successLowerBound (params : Parameters) : ℝ :=
  params.firstSuccessFactor * params.secondSuccessFactor

/-- Source real-valued group-operation upper bound
`8 c sqrt(N_{Delta,tau,t})` [E23, arxiv-v5.tex:1115-1127]. -/
noncomputable def groupOperationBound (params : Parameters) : ℝ :=
  (8 : ℝ) * params.c * Real.sqrt (params.searchSpace : ℝ)

/-- Source real-valued lookup-table upper bound
`8 sqrt(N_{Delta,tau,t}) / c + 3` [E23, arxiv-v5.tex:1115-1127]. -/
noncomputable def lookupTableBound (params : Parameters) : ℝ :=
  (8 : ℝ) * Real.sqrt (params.searchSpace : ℝ) / params.c + 3

end Parameters

/-- Source-scoped short-DLP instance: a cyclic group generator `g`, target
`x = g^d`, unknown order `r`, and the Ekera lower-bound side condition
`r >= 2^(m+ell) + (2^ell - 1)d` [E23, arxiv-v5.tex:1103-1117]. -/
structure SourceInstance (G : Type*) [Group G] (params : Parameters) where
  /-- Generator used by the short-DLP source instance. -/
  generator : G
  /-- Target group element for the short-DLP source instance. -/
  target : G
  /-- Known order of the generated subgroup. -/
  order : ℕ
  order_eq_orderOf : order = orderOf generator
  order_ne_zero : order ≠ 0
  /-- Discrete-logarithm witness used by the source instance. -/
  secret : ℕ
  secret_lt : secret < 2 ^ params.m
  target_eq_generator_pow : generator ^ secret = target
  order_lower_bound :
    2 ^ (params.m + params.ell) + (2 ^ params.ell - 1) * secret ≤ order

/-- Observed integer pair `(j, k)` yielded by the short-DLP quantum algorithm
before classical post-processing [E23, arxiv-v5.tex:1103-1117]. -/
structure SampledOutput (params : Parameters) where
  /-- First observed integer component. -/
  j : ℤ
  /-- Second observed integer component. -/
  k : ℤ

namespace SampledOutput

/-- Source expression `d j + 2^m k` used in the definition of a
`tau`-good pair [E23, arxiv-v5.tex:332-337]. -/
def tauGoodExpression {G : Type*} [Group G] {params : Parameters}
    (inst : SourceInstance G params) (sample : SampledOutput params) : ℤ :=
  (inst.secret : ℤ) * sample.j + ((2 : ℤ) ^ params.m) * sample.k

end SampledOutput

/-- Centered residue modulo `2^(m+ell)`, used to state the source
`tau`-good pair predicate without committing to an implementation of the
rounding algorithm [E23, arxiv-v5.tex:332-345]. -/
structure CenteredResidue (params : Parameters) (z : ℤ) where
  /-- Centered representative of `z` modulo `2^(m+ell)`. -/
  value : ℤ
  /-- Congruence to the original integer modulo the short-DLP modulus. -/
  congruent :
    ∃ a : ℤ, z = value + a * ((2 : ℤ) ^ (params.m + params.ell))

/-- Source predicate that the observed pair `(j, k)` is `tau`-good: the
centered representative of `d j + 2^m k` modulo `2^(m+ell)` has magnitude at
most `2^(m+tau)` [E23, arxiv-v5.tex:332-337]. -/
structure TauGoodPair {G : Type*} [Group G] {params : Parameters}
    (inst : SourceInstance G params) (sample : SampledOutput params) where
  /-- Centered representative of the tau-good expression. -/
  centered : CenteredResidue params (sample.tauGoodExpression inst)
  /-- The source tau-good magnitude bound. -/
  centered_abs_le : Int.natAbs centered.value ≤ 2 ^ (params.m + params.tau)

/-- Source predicate that the lattice `L^tau(j)` is `t`-balanced, represented
by its shortest non-zero vector norm. The lower bound matches the source
condition `lambda_1 >= 2^(m-t)` [E23, arxiv-v5.tex:655-663]. -/
structure TBalancedLattice (params : Parameters) (_sample : SampledOutput params) where
  /-- Norm of a shortest non-zero vector in `L^tau(j)`. -/
  shortestNonzeroNorm : ℝ
  /-- Source lower bound for `t`-balanced lattices. -/
  shortestNonzeroNorm_ge :
    (2 : ℝ) ^ (params.m - params.t) ≤ shortestNonzeroNorm

/-- Source good event for the E23 main theorem: the sampled output is
`tau`-good and the associated lattice is `t`-balanced [E23,
arxiv-v5.tex:1103-1128]. -/
structure GoodEvent {G : Type*} [Group G] {params : Parameters}
    (inst : SourceInstance G params) (sample : SampledOutput params) where
  /-- The observed pair is `tau`-good. -/
  tauGood : TauGoodPair inst sample
  /-- The associated lattice is `t`-balanced. -/
  balanced : TBalancedLattice params sample

/-- Source probability certificate for the E23 good-event predicates. This
records the probability model and the source lower-bound proof for observing a
sampled output that is both `tau`-good and `t`-balanced; recovery and resource
counts remain separate obligations [E23, arxiv-v5.tex:1103-1128]. -/
structure GoodEventMassCertificate {G : Type*} [Group G] {params : Parameters}
    (inst : SourceInstance G params) (Ω : Type*) where
  /-- Probability mass assigned to source-level sampling outcomes. -/
  prob : Ω → ℝ
  /-- Source probabilities are nonnegative. -/
  prob_nonneg : ∀ outcome, 0 ≤ prob outcome
  /-- Sampled short-DLP output for each source outcome. -/
  sample : Ω → SampledOutput params
  /-- Outcomes satisfying the E23 good-event predicates. -/
  goodEvents : Finset Ω
  /-- Every certified good event is `tau`-good and `t`-balanced. -/
  eventGood :
    ∀ outcome, outcome ∈ goodEvents → GoodEvent inst (sample outcome)
  /-- Success probability represented by the certified event mass. -/
  successProbability : ℝ
  /-- The represented probability is exactly the mass of the certified good event. -/
  successProbability_eq_goodMass :
    successProbability = goodEvents.sum prob
  /-- E23 lower bound for observing the combined good event. -/
  successProbability_ge :
    params.successLowerBound ≤ successProbability

namespace GoodEventMassCertificate

/-- The certified E23 good-event mass is at least the source lower bound. -/
theorem successProbability_ge_sourceLowerBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (cert : GoodEventMassCertificate inst Ω) :
    params.successLowerBound ≤ cert.successProbability :=
  cert.successProbability_ge

/-- The certified success probability is the sum of the good-event probability
mass. -/
private theorem successProbability_eq_sum
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (cert : GoodEventMassCertificate inst Ω) :
    cert.successProbability = cert.goodEvents.sum cert.prob :=
  cert.successProbability_eq_goodMass

/-- Every outcome in the certified good-event set is `tau`-good. -/
def tauGoodOfMemGoodEvents
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (cert : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ cert.goodEvents) :
    TauGoodPair inst (cert.sample outcome) :=
  (cert.eventGood outcome hmem).tauGood

/-- Every outcome in the certified good-event set has a `t`-balanced lattice. -/
def balancedOfMemGoodEvents
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (cert : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ cert.goodEvents) :
    TBalancedLattice params (cert.sample outcome) :=
  (cert.eventGood outcome hmem).balanced

end GoodEventMassCertificate

/-- Source enumeration window for the Ekerå short-DLP limited search.  The
fields record the integer bounds `B_1` and `B_2` used by the meet-in-the-middle
enumeration, together with the source side conditions `B_1 >= 1`,
`2 B_1 > B_2`, and `B_1 (B_2 + 1) < N_{Delta,tau,t}` [E23,
arxiv-v5.tex:760-783]. -/
structure LimitedSearchWindow (params : Parameters)
    (_sample : SampledOutput params) where
  /-- Source enumeration radius `B_1`. -/
  B1 : ℕ
  /-- Source enumeration radius `B_2`. -/
  B2 : ℕ
  /-- Source condition `B_1 >= 1`. -/
  B1_pos : 0 < B1
  /-- Source condition `2 B_1 > B_2`. -/
  B2_lt_two_mul_B1 : B2 < 2 * B1
  /-- Source bound `B_1 (B_2 + 1) < N_{Delta,tau,t}`. -/
  product_lt_searchSpace : B1 * (B2 + 1) < params.searchSpace

namespace LimitedSearchWindow

/-- The source product bound also yields a non-strict search-space upper bound. -/
private theorem product_le_searchSpace
    {params : Parameters} {sample : SampledOutput params}
    (window : LimitedSearchWindow params sample) :
    window.B1 * (window.B2 + 1) ≤ params.searchSpace :=
  Nat.le_of_lt window.product_lt_searchSpace

end LimitedSearchWindow

/-- Source-shaped construction data for the Ekerå limited-search recovery
algorithm.  The construction is attached to a certified good event, chooses the
meet-in-the-middle stride `n`, records the two lattice basis vectors and the
integer coefficients of the recovered candidate, and exposes the natural-number
operation counts as definitions from this construction rather than free fields
[E23, arxiv-v5.tex:825-872]. -/
structure LimitedSearchConstruction
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    (_event : GoodEvent inst sample) where
  /-- E23 enumeration window for the sampled output. -/
  window : LimitedSearchWindow params sample
  /-- Meet-in-the-middle stride `n = c round(sqrt(B_1/(B_2+1)))`. -/
  stride : ℕ
  /-- The source search stride is positive. -/
  stride_pos : 0 < stride
  /-- Origin vector of the lattice coset being enumerated. -/
  origin : ℤ × ℤ
  /-- First reduced lattice basis vector. -/
  firstBasis : ℤ × ℤ
  /-- Second reduced lattice basis vector. -/
  secondBasis : ℤ × ℤ
  /-- First integer coefficient selected by the limited search. -/
  firstIndex : ℤ
  /-- Second integer coefficient selected by the limited search. -/
  secondIndex : ℤ
  /-- Last component of the candidate lattice vector. -/
  candidateLastComponent : ℤ
  /-- The recovered candidate is the last component of the enumerated vector. -/
  candidateLastComponent_eq :
    candidateLastComponent =
      origin.2 + firstIndex * firstBasis.2 + secondIndex * secondBasis.2
  /-- Secret recovered by the source limited-search procedure. -/
  recoveredSecret : ℕ
  /-- The source limited search recovers the hidden short-DLP secret. -/
  recovered_eq_secret : recoveredSecret = inst.secret

namespace LimitedSearchConstruction

/-- Group operations in the first stage of the meet-in-the-middle search:
`2 (ceil(B_1/n) - 1)` [E23, arxiv-v5.tex:845-862]. -/
def firstStageGroupOperations
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) : ℕ :=
  2 * (QuantumAlg.Nat.ceilDiv construction.window.B1 construction.stride - 1)

/-- Group operations in the second stage of the meet-in-the-middle search:
`2 ((B_2 + 1)n - 1)` [E23, arxiv-v5.tex:863-872]. -/
def secondStageGroupOperations
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) : ℕ :=
  2 * ((construction.window.B2 + 1) * construction.stride - 1)

/-- Total group-operation count induced by the recorded limited-search
construction. -/
def groupOperations
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) : ℕ :=
  construction.firstStageGroupOperations + construction.secondStageGroupOperations

/-- Lookup-table size induced by the recorded limited-search construction:
`2 ceil(B_1/n) + 1` [E23, arxiv-v5.tex:845-849, 941-953]. -/
def lookupTableSize
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) : ℕ :=
  2 * QuantumAlg.Nat.ceilDiv construction.window.B1 construction.stride + 1

@[simp] theorem firstStageGroupOperations_eq
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) :
    construction.firstStageGroupOperations =
      2 * (QuantumAlg.Nat.ceilDiv construction.window.B1 construction.stride - 1) :=
  rfl

@[simp] theorem secondStageGroupOperations_eq
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) :
    construction.secondStageGroupOperations =
      2 * ((construction.window.B2 + 1) * construction.stride - 1) :=
  rfl

@[simp] theorem groupOperations_eq
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) :
    construction.groupOperations =
      construction.firstStageGroupOperations +
        construction.secondStageGroupOperations :=
  rfl

@[simp] theorem lookupTableSize_eq
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) :
    construction.lookupTableSize =
      2 * QuantumAlg.Nat.ceilDiv construction.window.B1 construction.stride + 1 :=
  rfl

/-- The source limited-search construction recovers the hidden short-DLP secret. -/
theorem recovers_secret
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (construction : LimitedSearchConstruction event) :
    construction.recoveredSecret = inst.secret :=
  construction.recovered_eq_secret

end LimitedSearchConstruction

/-- Source-backed E23 limited-search recovery/count witness.  The group and
lookup counts are not free fields: they are the values induced by the
`LimitedSearchConstruction`; this record adds the source inequalities bounding
those construction counts by Ekerå's explicit search-space formulas [E23,
arxiv-v5.tex:930-958]. -/
structure LimitedSearchRecoveryWitness
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    (event : GoodEvent inst sample) where
  /-- Limited-search construction that recovers the hidden secret. -/
  construction : LimitedSearchConstruction event
  /-- E23 source bound for the construction's group-operation count. -/
  groupOperations_le_sourceBound :
    (construction.groupOperations : ℝ) ≤ params.groupOperationBound
  /-- E23 source bound for the construction's lookup-table size. -/
  lookupTableSize_le_sourceBound :
    (construction.lookupTableSize : ℝ) ≤ params.lookupTableBound

namespace LimitedSearchRecoveryWitness

/-- Secret recovered by the limited-search witness. -/
def recoveredSecret
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) : ℕ :=
  witness.construction.recoveredSecret

/-- Group-operation count induced by the witness construction. -/
def groupOperations
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) : ℕ :=
  witness.construction.groupOperations

/-- Lookup-table size induced by the witness construction. -/
def lookupTableSize
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) : ℕ :=
  witness.construction.lookupTableSize

/-- The limited-search witness recovers the source secret. -/
theorem recovers_secret
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) :
    witness.recoveredSecret = inst.secret :=
  witness.construction.recovers_secret

/-- The witness's construction-derived group-operation count satisfies the
Ekerå source bound. -/
theorem groupOperations_count_le_sourceBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) :
    (witness.groupOperations : ℝ) ≤ params.groupOperationBound := by
  simpa [groupOperations] using witness.groupOperations_le_sourceBound

/-- The witness's construction-derived lookup-table size satisfies the Ekerå
source bound. -/
theorem lookupTableSize_count_le_sourceBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) :
    (witness.lookupTableSize : ℝ) ≤ params.lookupTableBound := by
  simpa [lookupTableSize] using witness.lookupTableSize_le_sourceBound

/-- Source recovery/count theorem for the limited-search step: under a certified
good event, the E23 limited search recovers the hidden secret and its
construction-derived group-operation and lookup-table counts satisfy the
source bounds [E23, arxiv-v5.tex:760-838, 930-958]. -/
theorem sourceRecoveryAndCountTheorem
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {sample : SampledOutput params}
    {event : GoodEvent inst sample}
    (witness : LimitedSearchRecoveryWitness event) :
    witness.recoveredSecret = inst.secret ∧
      (witness.groupOperations : ℝ) ≤ params.groupOperationBound ∧
      (witness.lookupTableSize : ℝ) ≤ params.lookupTableBound :=
  ⟨witness.recovers_secret, witness.groupOperations_le_sourceBound,
    witness.lookupTableSize_le_sourceBound⟩

end LimitedSearchRecoveryWitness

/-- A certificate that the classical short-DLP post-processing step recovers
the secret and satisfies the source probability/search/lookup bounds. The
probability and counting inequalities are data supplied by the source-facing
analysis; downstream RSA routes can consume the named projections below [E23,
arxiv-v5.tex:1103-1128]. -/
structure PostProcessingCertificate
    {G : Type*} [Group G] {params : Parameters}
    (inst : SourceInstance G params) where
  /-- J component of this record. -/
  j : ℤ
  /-- K component of this record. -/
  k : ℤ
  /-- Recovered secret component of this record. -/
  recoveredSecret : ℕ
  recovered_eq_secret : recoveredSecret = inst.secret
  /-- Success probability component of this record. -/
  successProbability : ℝ
  successProbability_ge :
    params.successLowerBound ≤ successProbability
  /-- Classical-operation count for group operations. -/
  groupOperations : ℕ
  groupOperations_le :
    (groupOperations : ℝ) ≤ params.groupOperationBound
  /-- Lookup table size component of this record. -/
  lookupTableSize : ℕ
  lookupTableSize_le :
    (lookupTableSize : ℝ) ≤ params.lookupTableBound

namespace PostProcessingCertificate

/-- Assemble the E23 short-DLP post-processing certificate from the formalized
good-event mass certificate and a limited-search recovery/count witness for one
certified good outcome.  This constructor is the internal source route: it
prevents downstream RSA endpoints from filling the post-processing fields
directly, while preserving the E23 success, group-operation, and lookup-table
bounds [E23, arxiv-v5.tex:760-838, 930-958, 1103-1128]. -/
def ofE23Source
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    PostProcessingCertificate inst where
  j := (mass.sample outcome).j
  k := (mass.sample outcome).k
  recoveredSecret := recovery.recoveredSecret
  recovered_eq_secret := recovery.recovers_secret
  successProbability := mass.successProbability
  successProbability_ge := mass.successProbability_ge_sourceLowerBound
  groupOperations := recovery.groupOperations
  groupOperations_le := recovery.groupOperations_count_le_sourceBound
  lookupTableSize := recovery.lookupTableSize
  lookupTableSize_le := recovery.lookupTableSize_count_le_sourceBound

@[simp] theorem ofE23Source_j
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).j = (mass.sample outcome).j :=
  rfl

@[simp] theorem ofE23Source_k
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).k = (mass.sample outcome).k :=
  rfl

@[simp] theorem ofE23Source_recoveredSecret
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).recoveredSecret =
      recovery.recoveredSecret :=
  rfl

@[simp] theorem ofE23Source_successProbability
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).successProbability =
      mass.successProbability :=
  rfl

@[simp] theorem ofE23Source_groupOperations
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).groupOperations =
      recovery.groupOperations :=
  rfl

@[simp] theorem ofE23Source_lookupTableSize
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).lookupTableSize =
      recovery.lookupTableSize :=
  rfl

/-- The E23 source constructor preserves secret recovery and all source
resource bounds. -/
private theorem ofE23Source_sourcePostprocessingTheorem
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params} {Ω : Type*}
    (mass : GoodEventMassCertificate inst Ω)
    {outcome : Ω} (hmem : outcome ∈ mass.goodEvents)
    (recovery : LimitedSearchRecoveryWitness (mass.eventGood outcome hmem)) :
    (ofE23Source mass hmem recovery).recoveredSecret = inst.secret ∧
      params.successLowerBound ≤
        (ofE23Source mass hmem recovery).successProbability ∧
      ((ofE23Source mass hmem recovery).groupOperations : ℝ) ≤
        params.groupOperationBound ∧
      ((ofE23Source mass hmem recovery).lookupTableSize : ℝ) ≤
        params.lookupTableBound :=
  ⟨by
      simpa [ofE23Source] using recovery.recovers_secret,
    by
      simpa [ofE23Source] using mass.successProbability_ge_sourceLowerBound,
    by
      simpa [ofE23Source] using recovery.groupOperations_count_le_sourceBound,
    by
      simpa [ofE23Source] using recovery.lookupTableSize_count_le_sourceBound⟩

/-- The certified post-processing output is the source secret `d`. -/
theorem recovers_secret
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params}
    (cert : PostProcessingCertificate inst) :
    cert.recoveredSecret = inst.secret :=
  cert.recovered_eq_secret

/-- The certified success probability is at least the Ekera source lower bound
[E23, arxiv-v5.tex:1108-1128]. -/
theorem successProbability_ge_sourceLowerBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params}
    (cert : PostProcessingCertificate inst) :
    params.successLowerBound ≤ cert.successProbability :=
  cert.successProbability_ge

/-- The certified number of group operations is bounded by the source search
expression `8 c sqrt(N_{Delta,tau,t})` [E23, arxiv-v5.tex:1115-1127]. -/
theorem groupOperations_le_sourceBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params}
    (cert : PostProcessingCertificate inst) :
    (cert.groupOperations : ℝ) ≤ params.groupOperationBound :=
  cert.groupOperations_le

/-- The certified lookup-table size is bounded by the source expression
`8 sqrt(N_{Delta,tau,t}) / c + 3` [E23, arxiv-v5.tex:1115-1127]. -/
theorem lookupTableSize_le_sourceBound
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params}
    (cert : PostProcessingCertificate inst) :
    (cert.lookupTableSize : ℝ) ≤ params.lookupTableBound :=
  cert.lookupTableSize_le

/-- Source-shaped short-DLP post-processing theorem: after the source side
conditions have been packaged in `Parameters` and `SourceInstance`, a
post-processing certificate recovers the secret and satisfies the explicit
success, group-operation, and lookup-table bounds from Ekera's theorem [E23,
arxiv-v5.tex:1103-1128]. -/
theorem sourcePostprocessingTheorem
    {G : Type*} [Group G] {params : Parameters}
    {inst : SourceInstance G params}
    (cert : PostProcessingCertificate inst) :
    cert.recoveredSecret = inst.secret ∧
      params.successLowerBound ≤ cert.successProbability ∧
      (cert.groupOperations : ℝ) ≤ params.groupOperationBound ∧
      (cert.lookupTableSize : ℝ) ≤ params.lookupTableBound :=
  ⟨cert.recovers_secret, cert.successProbability_ge_sourceLowerBound,
    cert.groupOperations_le_sourceBound, cert.lookupTableSize_le_sourceBound⟩

end PostProcessingCertificate

end ShortDLPPostprocessing

namespace LeanAbstraction

/-- Specialize a reusable cyclic abstraction to a source-scoped DLP instance at `target`. -/
def toSourceScope (A : LeanAbstraction G) (target : G) : SourceScope G where
  generator := A.generator
  target := target
  target_mem_zpowers := A.covers target

/-- The source-scope obligation induced by a reusable cyclic abstraction. -/
private theorem target_mem_zpowers (A : LeanAbstraction G) (target : G) :
    target ∈ Subgroup.zpowers A.generator :=
  A.covers target

/-- Candidate notation for a target specialized from the reusable abstraction. -/
def CandidateScalar (A : LeanAbstraction G) (target : G) (x : ℕ) : Prop :=
  (A.toSourceScope target).CandidateScalar x

end LeanAbstraction

end FiniteCyclicDLP
end QuantumAlg
