/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Util.ResidueEncoding

/-!
# Modular multiplication domain choice

This module fixes the carrier convention for the order-finding modular
multiplication unitary. The mathematical action is on the unit group
`(ZMod N)^x`; binary register labels are only the computational-basis storage
layer supplied by `BinaryResidueEncoding`.

The generated cyclic subgroup of a chosen unit is a derived carrier for
eigenstate work, not the primary domain of `U_a`.

This carrier choice is the Lean-side domain convention for Shor's modular
multiplication unitary in order finding [Sho95, source.tex:1124-1134] [dW19,
qcnotes.tex:2469-2475].
-/

@[expose] public section

namespace QuantumAlg

/-- Candidate carriers considered for the order-finding modular multiplication
unitary. -/
inductive ModularMultiplicationCarrier where
  /-- The residue ring `ZMod N`; too broad for multiplication by a non-unit. -/
  | residueRing
  /-- The unit group `(ZMod N)^x`; selected for `U_a`. -/
  | unitGroup
  /-- The cyclic subgroup generated by the selected unit; used for eigenstates. -/
  | generatedCyclicSubgroup
deriving DecidableEq, Repr

/-- Domain convention for modular multiplication over a binary residue
register. -/
structure ModularMultiplicationDomain (N n : ℕ) extends BinaryResidueEncoding N n where

namespace ModularMultiplicationDomain

/-- The selected mathematical carrier for `U_a`. -/
def selectedCarrier {_N _n : ℕ} (D : ModularMultiplicationDomain _N _n) :
    ModularMultiplicationCarrier :=
  let _h := D.modulus_pos
  .unitGroup

/-- Mathematical carrier for the modular multiplication action. -/
abbrev UnitCarrier {N n : ℕ} (D : ModularMultiplicationDomain N n) : Type :=
  let _h := D.modulus_pos
  (ZMod N)ˣ

/-- Register-label carrier used by computational-basis states. -/
abbrev RegisterLabel {N n : ℕ} (D : ModularMultiplicationDomain N n) : Type :=
  let _h := D.register_fits
  Fin (2 ^ n)

/-- Residue-ring carrier used only as the decode target for register labels. -/
abbrev ResidueCarrier {N n : ℕ} (D : ModularMultiplicationDomain N n) : Type :=
  let _h := D.modulus_pos
  ZMod N

/-- Cyclic subgroup generated by a selected unit. This is the carrier for the
eigenbasis layer, derived from the unit-group action. -/
abbrev CyclicSubgroupCarrier {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) : Type :=
  Subgroup.zpowers u

/-- Coerce a unit-group element to the residue ring. -/
def unitResidue {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) : ZMod N :=
  (u : ZMod N)

/-- Promote a natural number coprime to the modulus into the selected unit
carrier. This is the entry point for source statements that provide
`Nat.Coprime a N` rather than an explicit unit. -/
def unitOfCoprime {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a : ℕ) (ha : Nat.Coprime a N) : UnitCarrier D :=
  ZMod.unitOfCoprime a ha

/-- Multiplication by a selected unit on the chosen mathematical carrier. -/
def multiplyUnit {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a x : UnitCarrier D) : UnitCarrier D :=
  a * x

/-- The permutation underlying modular multiplication by a selected unit. Its
inverse is multiplication by `a^-1`, so no stronger assumption than membership
in `(ZMod N)^x` is needed. -/
def multiplicationPerm {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a : UnitCarrier D) : Equiv.Perm (UnitCarrier D) where
  toFun := fun x => D.multiplyUnit a x
  invFun := fun x => D.multiplyUnit a⁻¹ x
  left_inv x := by
    simp [multiplyUnit]
  right_inv x := by
    simp [multiplyUnit]

/-- Encode a unit-group element as the canonical computational-basis label of
its residue. -/
def canonicalLabel {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) : RegisterLabel D :=
  D.toBinaryResidueEncoding.encode (u : ZMod N)

@[simp]
theorem selectedCarrier_eq_unitGroup {N n : ℕ} (D : ModularMultiplicationDomain N n) :
    D.selectedCarrier = .unitGroup := rfl

@[simp]
theorem unitResidue_eq_coe {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) :
    D.unitResidue u = (u : ZMod N) := rfl

@[simp]
theorem unitOfCoprime_coe {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a : ℕ) (ha : Nat.Coprime a N) :
    (D.unitOfCoprime a ha : ZMod N) = a :=
  ZMod.coe_unitOfCoprime a ha

@[simp]
theorem multiplyUnit_apply {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a x : UnitCarrier D) :
    D.multiplyUnit a x = a * x := rfl

@[simp]
theorem multiplicationPerm_apply {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a x : UnitCarrier D) :
    D.multiplicationPerm a x = a * x := rfl

@[simp]
theorem multiplicationPerm_symm_apply {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a x : UnitCarrier D) :
    (D.multiplicationPerm a).symm x = a⁻¹ * x := rfl

private theorem multiplyUnit_bijective {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (a : UnitCarrier D) :
    Function.Bijective (D.multiplyUnit a) :=
  (D.multiplicationPerm a).bijective

/-- Canonical labels for units are valid residue-register labels. -/
private theorem canonicalLabel_valid {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) :
    D.toBinaryResidueEncoding.IsValid (D.canonicalLabel u) :=
  D.toBinaryResidueEncoding.encode_isValid (u : ZMod N)

@[simp]
theorem decode_canonicalLabel {N n : ℕ} (D : ModularMultiplicationDomain N n)
    (u : UnitCarrier D) :
    D.toBinaryResidueEncoding.decode (D.canonicalLabel u) = (u : ZMod N) := by
  simp [canonicalLabel]

end ModularMultiplicationDomain

end QuantumAlg
