/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Algorithms.FiniteCyclicDLP
public import QuantumAlg.Algorithms.Factoring.Common
public import QuantumAlg.Primitives.EllipticCurve.ScalarMultiplicationEndpoint
public import QuantumAlg.Primitives.EllipticCurve.ScalarMultiplication.StructuredCircuit

/-!
# Elliptic-curve discrete-logarithm endpoint

This module connects the finite-cyclic DLP endpoint to the prime-field
elliptic-curve scalar-recovery problem.  The bridge is deliberately explicit:
the current affine circuit layer has a certified generic scalar-multiplication
endpoint, but it does not yet install a complete elliptic-curve group instance
for all finite points.  A `FiniteCyclicBridge` therefore records exactly how a
finite-cyclic recovered residue is interpreted as an ECDLP candidate scalar.

The source route matches the Proos--Zalka elliptic-curve discrete-logarithm
problem statement [PZ03, ecc.tex:144-188], reuses Shor's finite-cyclic DLP
sampling endpoint [Sho95, source.tex:1704-1784], and keeps the reversible
affine scalar-multiplication resource boundary aligned with the Roetteler--
Naehrig--Svore--Lauter baseline route [RNSL17, ECDLP.tex:129-194].
-/

@[expose] public section

namespace QuantumAlg
namespace EllipticCurve
namespace PrimeFieldShortWeierstrass
namespace ECDLP

universe u v

/-- Cast a recovered finite-cyclic residue along an equality of subgroup orders. -/
def castScalar {n m : Nat} (h : n = m) (x : ZMod n) : ZMod m := by
  cases h
  exact x

@[simp] theorem castScalar_rfl {n : Nat} (x : ZMod n) :
    castScalar rfl x = x :=
  rfl

/-- Certificate that a finite-cyclic DLP instance represents the same scalar
recovery problem as an elliptic-curve discrete-logarithm instance.  The
certificate keeps the subgroup-order identification and the final candidate
scalar obligation explicit, rather than assuming a global affine point group
instance that this development has not installed. -/
structure FiniteCyclicBridge {p : Nat} {E : PrimeFieldShortWeierstrass p}
    (I : ECDLPInstance E) {G : Type u} [Group G]
    (P : QuantumAlg.FiniteCyclicDLP.KnownOrderProblem G)
    (secret : ZMod P.order) where
  /-- The finite-cyclic DLP order is the ECDLP subgroup order. -/
  order_eq : P.order = I.subgroupOrder
  /-- Interpretation of finite-cyclic group labels as finite elliptic-curve
  points.  A later subgroup-isomorphism layer can instantiate this map; the
  present endpoint keeps it as explicit data. -/
  interpret : G → FinitePoint E
  /-- The finite-cyclic generator is the selected ECDLP base point. -/
  generator_interprets_base : interpret P.generator = I.basePoint
  /-- The finite-cyclic target is the selected ECDLP target point. -/
  target_interprets_target : interpret P.target = I.targetPoint
  /-- The finite-cyclic hidden target is generated by the same secret recovered
  by the finite-cyclic DLP endpoint. -/
  target_eq_generator_pow_secret : P.target = P.generator ^ secret.val
  /-- Powers of the finite-cyclic generator agree with the supplied ECDLP scalar
  multiplication map after transporting residues across `order_eq`. -/
  scalar_compat :
    ∀ k : ZMod P.order,
      interpret (P.generator ^ k.val) =
        I.scalarMultiplication (castScalar order_eq k)

namespace FiniteCyclicBridge

variable {p : Nat} {E : PrimeFieldShortWeierstrass p}
variable {I : ECDLPInstance E} {G : Type u} [Group G]
variable {P : QuantumAlg.FiniteCyclicDLP.KnownOrderProblem G}
variable {secret : ZMod P.order}

/-- The source hidden scalar, transported across the subgroup-order equality,
solves the ECDLP target equation. -/
theorem secret_candidate (bridge : FiniteCyclicBridge I P secret) :
    I.CandidateScalar (castScalar bridge.order_eq secret) := by
  dsimp [ECDLPInstance.CandidateScalar]
  have htarget :
      bridge.interpret (P.generator ^ secret.val) = I.targetPoint := by
    exact
      (congrArg bridge.interpret bridge.target_eq_generator_pow_secret).symm.trans
        bridge.target_interprets_target
  exact (bridge.scalar_compat secret).symm.trans htarget

/-- Interpret a finite-cyclic DLP output as an ECDLP scalar. -/
def toECDLPScalar (bridge : FiniteCyclicBridge I P secret)
    (output : ZMod P.order) : ZMod I.subgroupOrder :=
  castScalar bridge.order_eq output

/-- A finite-cyclic output equal to the source secret gives an ECDLP candidate
scalar. -/
theorem toECDLPScalar_candidate_of_eq_secret
    (bridge : FiniteCyclicBridge I P secret) {output : ZMod P.order}
    (houtput : output = secret) :
    I.CandidateScalar (bridge.toECDLPScalar output) := by
  subst output
  simpa [toECDLPScalar] using bridge.secret_candidate

end FiniteCyclicBridge

/-- Scalar-multiplication oracle resource evidence consumed by the ECDLP
endpoint.  This is a thin wrapper around the certified affine scalar endpoint:
it carries a concrete schedule, source-count parameters, public bounds, and
the source-bound proof connecting the two. -/
structure ScalarOracleResourceCertificate {p : Nat}
    (E : PrimeFieldShortWeierstrass p) where
  /-- Fixed affine controlled-addition schedule used by the scalar oracle. -/
  schedule : ScalarMultiplication.Schedule E
  /-- Exact component resource parameters for the certified scalar endpoint. -/
  params : ScalarMultiplication.CertifiedEndpoint.ResourceParameters
  /-- Public baseline bounds against which the endpoint resources are checked. -/
  bounds :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.PublicBaselineBounds
  /-- Source-bound proof connecting exact component parameters to public bounds. -/
  sourceBounds :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SourceBoundCertificate
      schedule params bounds

namespace ScalarOracleResourceCertificate

variable {p : Nat} {E : PrimeFieldShortWeierstrass p}

/-- Exact scalar-oracle profile induced by the selected affine schedule. -/
def profile (cert : ScalarOracleResourceCertificate E) :
    ModularArithmeticResourceProfile :=
  cert.params.toProfile cert.schedule

/-- Public scalar-oracle bound profile induced by the selected source bounds. -/
def boundProfile (cert : ScalarOracleResourceCertificate E) :
    ModularArithmeticResourceProfile :=
  cert.bounds.toProfile

/-- The selected scalar-oracle profile supports its public baseline bounds. -/
theorem supportsPublicBaseline (cert : ScalarOracleResourceCertificate E) :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
      cert.schedule cert.profile cert.bounds :=
  cert.sourceBounds.supportsPublicBaseline

/-- Fieldwise upper-bound evidence for the selected scalar-oracle profile. -/
theorem supportsUpperBound (cert : ScalarOracleResourceCertificate E) :
    ModularArithmeticResourceProfile.SupportsUpperBound
      cert.profile cert.boundProfile :=
  cert.sourceBounds.supportsUpperBound

end ScalarOracleResourceCertificate

/-! ## Same-circuit scalar-oracle resource witness -/

/-- Natural-number resource fields projected from a decomposed base-gate
elliptic-curve scalar-multiplication witness.  In the base-gate model the
single-qubit field counts X/NOT atoms, since the accepted structured circuit
leaves are only X, CNOT, and Toffoli. -/
structure SameCircuitResourceFields where
  /-- Logical qubits used by the decomposed scalar circuit. -/
  logicalQubits : Nat
  /-- Toffoli atoms in the decomposed scalar circuit. -/
  toffoliGates : Nat
  /-- CNOT atoms in the decomposed scalar circuit. -/
  cnotGates : Nat
  /-- X/NOT atoms in the decomposed scalar circuit. -/
  xGates : Nat
  /-- Maximal circuit depth projected from the decomposed scalar circuit. -/
  circuitDepth : Nat
  /-- Toffoli-depth component projected from the decomposed scalar circuit. -/
  toffoliDepth : Nat
  /-- Structured classical arithmetic operations attached to the same profile. -/
  classicalOps : Nat
deriving DecidableEq

namespace SameCircuitResourceFields

/-- Project the public natural-number fields from a structured arithmetic
profile. -/
def ofProfile (profile : ModularArithmeticResourceProfile) :
    SameCircuitResourceFields where
  logicalQubits := profile.logicalQubits
  toffoliGates := profile.toffoliGates
  cnotGates := profile.cnotGates
  xGates := profile.singleQubitGates
  circuitDepth := profile.circuitDepth
  toffoliDepth := profile.toffoliDepth
  classicalOps := profile.classicalArithmetic.total

/-- Fieldwise exactness of the public scalar-recovery resource fields against
the underlying same-circuit modular-arithmetic profile. -/
def ExactForProfile
    (fields : SameCircuitResourceFields)
    (profile : ModularArithmeticResourceProfile) : Prop :=
  fields.logicalQubits = profile.logicalQubits ∧
    fields.toffoliGates = profile.toffoliGates ∧
    fields.cnotGates = profile.cnotGates ∧
    fields.xGates = profile.singleQubitGates ∧
    fields.circuitDepth = profile.circuitDepth ∧
    fields.toffoliDepth = profile.toffoliDepth ∧
    fields.classicalOps = profile.classicalArithmetic.total

@[simp] theorem ofProfile_exact (profile : ModularArithmeticResourceProfile) :
    ExactForProfile (ofProfile profile) profile := by
  simp [ExactForProfile, ofProfile]

end SameCircuitResourceFields

/-- Scalar-multiplication oracle evidence whose correctness and resource
projection are derived from one decomposed Toffoli/CNOT/X circuit.  The witness
keeps the old public-bound component certificate, but additionally records that
the exact profile used for those bounds is the profile projected from the same
folded circuit that supplies encoded-basis correctness. -/
structure SameCircuitScalarOracleCertificate {p : Nat}
    (E : PrimeFieldShortWeierstrass p) [Fact p.Prime] where
  /-- Fixed affine controlled-addition schedule used by the scalar oracle. -/
  schedule : ScalarMultiplication.Schedule E
  /-- Certified scalar action implemented by the decomposed endpoint. -/
  action : ScalarMultiplication.CertifiedScalarAction E schedule
  /-- Decomposed endpoint witness assembled from structured controlled ECADD
  and scalar-multiplication layers. -/
  endpointWitness :
    ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness
      E schedule action
  /-- Exact component resource parameters used for the public-bound bridge. -/
  params : ScalarMultiplication.CertifiedEndpoint.ResourceParameters
  /-- Public baseline bounds against which the endpoint resources are checked. -/
  bounds :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.PublicBaselineBounds
  /-- Source-bound proof connecting exact component parameters to public bounds. -/
  sourceBounds :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SourceBoundCertificate
      schedule params bounds
  /-- The component-resource profile is the one projected from the same folded
  decomposed circuit witness. -/
  profile_eq_params :
    BaseGateSameCircuitWitness.profile endpointWitness.sameCircuit =
      params.toProfile schedule

namespace SameCircuitScalarOracleCertificate

variable {p : Nat} {E : PrimeFieldShortWeierstrass p} [Fact p.Prime]

/-- The same-Circuit witness supplied by the decomposed scalar endpoint. -/
def sameCircuit (cert : SameCircuitScalarOracleCertificate E) :=
  cert.endpointWitness.sameCircuit

/-- The folded scalar-multiplication circuit shared by correctness and
resource projection. -/
def circuit (cert : SameCircuitScalarOracleCertificate E) :
    Circuit (Qubits cert.endpointWitness.encoding.width) :=
  BaseGateSameCircuitWitness.circuit cert.sameCircuit

/-- Exact scalar-oracle profile projected from the same folded circuit object. -/
def profile (cert : SameCircuitScalarOracleCertificate E) :
    ModularArithmeticResourceProfile :=
  BaseGateSameCircuitWitness.profile cert.sameCircuit

/-- Public scalar-oracle bound profile induced by the selected source bounds. -/
def boundProfile (cert : SameCircuitScalarOracleCertificate E) :
    ModularArithmeticResourceProfile :=
  cert.bounds.toProfile

/-- Natural-number resource fields projected from the same folded circuit
object. -/
def resourceFields (cert : SameCircuitScalarOracleCertificate E) :
    SameCircuitResourceFields :=
  SameCircuitResourceFields.ofProfile cert.profile

/-- Forget the same-circuit witness and keep the older scalar-oracle resource
certificate interface. -/
def toResourceCertificate (cert : SameCircuitScalarOracleCertificate E) :
    ScalarOracleResourceCertificate E where
  schedule := cert.schedule
  params := cert.params
  bounds := cert.bounds
  sourceBounds := cert.sourceBounds

/-- The folded scalar circuit history bottoms out in X/CNOT/Toffoli atoms. -/
theorem structured (cert : SameCircuitScalarOracleCertificate E) :
    cert.circuit.history.IsBaseGateStructured :=
  ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness.structured
    cert.endpointWitness

/-- Resource counters are projected from the same folded scalar circuit used
for encoded-basis correctness. -/
theorem resources_eq (cert : SameCircuitScalarOracleCertificate E) :
    cert.circuit.resources = cert.profile.toResourceProfile :=
  ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness.resources_eq
    cert.endpointWitness

/-- Circuit depth is projected from the same folded scalar circuit. -/
theorem depth_eq (cert : SameCircuitScalarOracleCertificate E) :
    cert.circuit.depth = cert.profile.circuitDepth :=
  ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness.depth_eq
    cert.endpointWitness

/-- Query depth is projected from the same folded scalar circuit. -/
theorem queryDepth_eq (cert : SameCircuitScalarOracleCertificate E) :
    cert.circuit.queryDepth = cert.profile.oracleQueries :=
  ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness.queryDepth_eq
    cert.endpointWitness

/-- Resource-correct witness for the decomposed scalar endpoint. -/
def resourceCorrectWitness (cert : SameCircuitScalarOracleCertificate E) :
    ResourceCorrectWitness
      (R := Qubits cert.endpointWitness.encoding.width)
      (∀ x :
        ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.State
          E cert.schedule cert.action,
        Circuit.apply cert.circuit
          ((PureState.ket (R := Qubits cert.endpointWitness.encoding.width)
            (cert.endpointWitness.encoding.encode x) :
            PureState (Qubits cert.endpointWitness.encoding.width)) :
            StateVector (Qubits cert.endpointWitness.encoding.width)) =
          (PureState.ket (R := Qubits cert.endpointWitness.encoding.width)
            (cert.endpointWitness.encoding.encode
              (ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.fullStep
                E cert.schedule cert.action x)) :
            StateVector (Qubits cert.endpointWitness.encoding.width)))
      (cert.circuit.resources = cert.profile.toResourceProfile ∧
        cert.circuit.depth = cert.profile.circuitDepth ∧
        cert.circuit.queryDepth = cert.profile.oracleQueries) :=
  ScalarMultiplication.CertifiedEndpoint.ComposedEndpoint.Witness.resourceCorrectWitness
    cert.endpointWitness

/-- The resource-correct witness exposes the same folded scalar circuit. -/
@[simp] theorem resourceCorrectWitness_circuit
    (cert : SameCircuitScalarOracleCertificate E) :
    cert.resourceCorrectWitness.circuit = cert.circuit :=
  rfl

/-- The exact natural-number resource fields match the profile projected from
the same scalar circuit. -/
theorem resourceFields_exact (cert : SameCircuitScalarOracleCertificate E) :
    SameCircuitResourceFields.ExactForProfile cert.resourceFields cert.profile :=
  SameCircuitResourceFields.ofProfile_exact cert.profile

@[simp] theorem resourceFields_classicalOps
    (cert : SameCircuitScalarOracleCertificate E) :
    cert.resourceFields.classicalOps = cert.profile.classicalArithmetic.total :=
  rfl

/-- The same-circuit scalar profile supports the selected public baseline. -/
theorem supportsPublicBaseline
    (cert : SameCircuitScalarOracleCertificate E) :
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
      cert.schedule cert.profile cert.bounds := by
  change
    ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
      cert.schedule
      (BaseGateSameCircuitWitness.profile cert.endpointWitness.sameCircuit)
      cert.bounds
  rw [cert.profile_eq_params]
  exact cert.sourceBounds.supportsPublicBaseline

/-- The same-circuit scalar profile is bounded by the selected public profile. -/
theorem supportsUpperBound
    (cert : SameCircuitScalarOracleCertificate E) :
    ModularArithmeticResourceProfile.SupportsUpperBound
      cert.profile cert.boundProfile := by
  change
    ModularArithmeticResourceProfile.SupportsUpperBound
      (BaseGateSameCircuitWitness.profile cert.endpointWitness.sameCircuit)
      cert.bounds.toProfile
  rw [cert.profile_eq_params]
  exact cert.sourceBounds.supportsUpperBound

end SameCircuitScalarOracleCertificate

/-! ## Success amplification against a rational failure budget -/

namespace SuccessAmplification

/-- Retry multiplier for an ECC scalar-recovery statement with target failure
budget `eta`.  The run count is an explicit upper-bound parameter: the
probability derivation that repeated Shor-style DLP experiments reach the
selected failure budget is carried by `EtaCertificate`, following the repeated
sampling analysis in Shor's discrete-logarithm route [Sho95,
source.tex:1924-1987]. -/
def etaRetrySpec (eta : Factoring.FailureBudget) (runCount : Nat) :
    Factoring.RetryMultiplierSpec :=
  Factoring.RetryMultiplierSpec.explicitUpperBound eta runCount

@[simp] theorem etaRetrySpec_failureBudget
    (eta : Factoring.FailureBudget) (runCount : Nat) :
    (etaRetrySpec eta runCount).failureBudget = eta :=
  rfl

@[simp] theorem etaRetrySpec_runCount
    (eta : Factoring.FailureBudget) (runCount : Nat) :
    (etaRetrySpec eta runCount).runCount = runCount :=
  rfl

@[simp] theorem etaRetrySpec_ready
    (eta : Factoring.FailureBudget) (runCount : Nat) :
    (etaRetrySpec eta runCount).readyForFinalStatement = true :=
  rfl

/-- Source-facing amplification certificate for an ECC scalar-recovery theorem
with rational target failure budget `eta`.  The certificate keeps the
probability model explicit: Lean records the repeated-run failure fraction,
its comparison with `eta`, and a natural-number retry upper-bound parameter
provided by the source-facing certificate. -/
structure EtaCertificate (eta : Factoring.FailureBudget) where
  /-- Concrete repeated-run count used by the amplified statement. -/
  runCount : Nat
  /-- Natural-number upper bound for the selected retry expression.  Source
  certificates may choose this parameter to record logarithmic dependence on
  the target failure budget. -/
  logInvEtaUpperBound : Nat
  /-- The target failure budget is a valid rational number in `[0, 1]`. -/
  eta_wellFormed : eta.WellFormed
  /-- At least one run is performed. -/
  runCount_pos : 0 < runCount
  /-- The concrete run count is bounded by the selected logarithmic expression. -/
  runCount_le_logInvEtaUpperBound : runCount ≤ logInvEtaUpperBound
  /-- Source-certified repeated-run failure probability for this retry
  multiplier. -/
  repetitionModel :
    Factoring.RetryMultiplierSpec.RepetitionModel (etaRetrySpec eta runCount)

namespace EtaCertificate

variable {eta : Factoring.FailureBudget}

/-- Retry multiplier encoded by an eta-amplification certificate. -/
def retrySpec (cert : EtaCertificate eta) : Factoring.RetryMultiplierSpec :=
  etaRetrySpec eta cert.runCount

@[simp] theorem retrySpec_failureBudget (cert : EtaCertificate eta) :
    cert.retrySpec.failureBudget = eta :=
  rfl

@[simp] theorem retrySpec_runCount (cert : EtaCertificate eta) :
    cert.retrySpec.runCount = cert.runCount :=
  rfl

@[simp] theorem retrySpec_ready (cert : EtaCertificate eta) :
    cert.retrySpec.readyForFinalStatement = true :=
  rfl

/-- The repeated-run failure fraction certified by the source model is at most
the requested eta budget. -/
theorem repeatedFailure_le_eta (cert : EtaCertificate eta) :
    cert.repetitionModel.failureNumerator * eta.failureDenominator ≤
      eta.failureNumerator * cert.repetitionModel.failureDenominator := by
  simpa [retrySpec, etaRetrySpec, Factoring.RetryMultiplierSpec.explicitUpperBound] using
    Factoring.RetryMultiplierSpec.RepetitionModel.satisfies_failureBudget
      cert.repetitionModel

/-- Eta certificates discharge the generic retry well-formedness obligations. -/
private theorem toRetryWellFormed (cert : EtaCertificate eta) :
    Factoring.RetryMultiplierSpec.WellFormed cert.retrySpec := by
  exact
    { failureBudget_wellFormed := cert.eta_wellFormed
      runCount_pos := by
        simpa [retrySpec] using cert.runCount_pos
      ready := by
        simp [retrySpec] }

/-- Apply the eta retry multiplier to a per-run modular-arithmetic profile. -/
def successAccountedProfile (cert : EtaCertificate eta)
    (perRun : ModularArithmeticResourceProfile) :
    ModularArithmeticResourceProfile :=
  cert.retrySpec.successAccountedProfile perRun

@[simp] theorem successAccountedProfile_toffoliGates
    (cert : EtaCertificate eta) (perRun : ModularArithmeticResourceProfile) :
    (cert.successAccountedProfile perRun).toffoliGates =
      cert.runCount * perRun.toffoliGates := by
  simpa [successAccountedProfile, retrySpec] using
    Factoring.RetryMultiplierSpec.successAccountedProfile_toffoliGates
      cert.retrySpec perRun

@[simp] theorem successAccountedProfile_toffoliDepth
    (cert : EtaCertificate eta) (perRun : ModularArithmeticResourceProfile) :
    (cert.successAccountedProfile perRun).toffoliDepth =
      cert.runCount * perRun.toffoliDepth := by
  cases hrun : cert.runCount <;>
    simp [successAccountedProfile, retrySpec,
      Factoring.RetryMultiplierSpec.successAccountedProfile,
      ModularArithmeticResourceProfile.repeatSequential,
      ModularArithmeticResourceProfile.zero, hrun]

@[simp] theorem successAccountedProfile_circuitDepth
    (cert : EtaCertificate eta) (perRun : ModularArithmeticResourceProfile) :
    (cert.successAccountedProfile perRun).circuitDepth =
      cert.runCount * perRun.circuitDepth := by
  simpa [successAccountedProfile, retrySpec] using
    Factoring.RetryMultiplierSpec.successAccountedProfile_circuitDepth
      cert.retrySpec perRun

@[simp] theorem successAccountedProfile_logicalQubits
    (cert : EtaCertificate eta) (perRun : ModularArithmeticResourceProfile) :
    (cert.successAccountedProfile perRun).logicalQubits =
      perRun.logicalQubits := by
  have hpos : 0 < cert.retrySpec.runCount := by
    simpa [retrySpec] using cert.runCount_pos
  simpa [successAccountedProfile] using
    Factoring.RetryMultiplierSpec.successAccountedProfile_logicalQubits_of_pos
      cert.retrySpec perRun hpos

/-- Fieldwise upper bounds are preserved by eta retry scaling. -/
private theorem successAccountedProfile_supportsUpperBound
    (cert : EtaCertificate eta)
    {profile bound : ModularArithmeticResourceProfile}
    (h : ModularArithmeticResourceProfile.SupportsUpperBound profile bound) :
    ModularArithmeticResourceProfile.SupportsUpperBound
      (cert.successAccountedProfile profile)
      (cert.successAccountedProfile bound) := by
  simpa [successAccountedProfile, retrySpec] using
    ModularArithmeticResourceProfile.SupportsUpperBound.repeatSequential
      (k := cert.retrySpec.runCount) h

end EtaCertificate
end SuccessAmplification

/-- ECDLP scalar-recovery endpoint from finite-cyclic Fourier-sampling support.
Good finite-cyclic recovery outputs are transported through the bridge into
candidate elliptic-curve scalars, while the resource side keeps both the DLP
public-bound certificate and the reversible scalar-oracle bound certificate
visible. -/
theorem main_with_public_bounds_of_fourier_sampling_support
    {p : Nat} {E : PrimeFieldShortWeierstrass p} {I : ECDLPInstance E}
    {G : Type u} [Group G]
    {P : QuantumAlg.FiniteCyclicDLP.KnownOrderProblem G} {Ω : Type v}
    (support : QuantumAlg.FiniteCyclicDLP.FourierSamplingSupport P Ω)
    (bridge : FiniteCyclicBridge I P support.secret)
    (scalarOracle : ScalarOracleResourceCertificate E)
    (params : QuantumAlg.FiniteCyclicDLP.ResourceParameters)
    (bounds : QuantumAlg.FiniteCyclicDLP.PublicBaselineBounds.FormulaParameters)
    (horderBits : params.orderRegisterQubits ≤ bounds.orderBitUpperBound)
    (hgroup : params.groupRegisterQubits ≤ bounds.groupRegisterQubitBound)
    (horacleDepth : params.oracleDepth ≤ bounds.oracleDepthBound)
    (hfourierDepth : params.fourierLayerDepth ≤ bounds.fourierLayerDepthBound)
    (hclassical :
      params.classicalPostProcessing.total ≤ bounds.classicalOperationBound) :
    let sampling : QuantumAlg.FiniteCyclicDLP.SamplingCertificate P Ω :=
      support.toSamplingCertificate
    (∀ outcome (hgood : outcome ∈ sampling.goodEvents),
      I.CandidateScalar
        (bridge.toECDLPScalar ((sampling.recovery outcome hgood).output))) ∧
      sampling.SuccessAtLeastTwoThirds ∧
      (2 : ℝ) / 3 ≤ sampling.goodMass ∧
      (sampling.successNumerator : ℝ) /
          (sampling.successDenominator : ℝ) ≤ sampling.goodMass ∧
      0 ≤ sampling.goodMass ∧
      sampling.goodMass ≤ 1 ∧
      QuantumAlg.FiniteCyclicDLP.ExactResourceProfile.HasExactCounts
        params.toExactResourceProfile
        1
        (2 * params.orderRegisterQubits + params.groupRegisterQubits)
        (2 * params.orderRegisterQubits)
        (params.orderRegisterQubits * (params.orderRegisterQubits - 1))
        (2 * (params.orderRegisterQubits / 2))
        (params.oracleDepth + params.fourierLayerDepth)
        params.classicalPostProcessing.total ∧
      QuantumAlg.FiniteCyclicDLP.SupportsPublicBaseline
        params.toExactResourceProfile bounds.toPublicBaselineBounds ∧
      ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
        scalarOracle.schedule scalarOracle.profile scalarOracle.bounds ∧
      ModularArithmeticResourceProfile.SupportsUpperBound
        scalarOracle.profile scalarOracle.boundProfile := by
  dsimp
  refine
    ⟨?_, support.toSamplingCertificate.successAtLeastTwoThirds,
      support.toSamplingCertificate.twoThirds_le_goodMass,
      support.toSamplingCertificate.rationalBound_le_goodMass',
      support.toSamplingCertificate.goodMass_nonneg,
      support.toSamplingCertificate.goodMass_le_one',
      params.toExactResourceProfile_hasExactCounts,
      QuantumAlg.FiniteCyclicDLP.supportsPublicBaseline_of_formulaBounds
        horderBits hgroup horacleDepth hfourierDepth hclassical,
      scalarOracle.supportsPublicBaseline, scalarOracle.supportsUpperBound⟩
  intro outcome hgood
  open FiniteCyclicDLP.RecoverableFourierSample in
  exact bridge.toECDLPScalar_candidate_of_eq_secret (by
    simpa [FiniteCyclicDLP.FourierSamplingSupport.toSamplingCertificate,
      FiniteCyclicDLP.SamplingCertificate.ofLeftUnitAddEqZero,
      RecoveryCertificate.ofLeftUnitAndAddEqZero,
      RecoveryCertificate.ofLeftUnitAndLinearRelation] using
      support.toSamplingCertificate.recovery_output_eq_secret outcome hgood)

/-- ECDLP scalar-recovery endpoint with a decomposed same-circuit scalar oracle.
Finite-cyclic Fourier-sampling supplies the success and candidate-scalar
correctness; the scalar-oracle resource side is projected from one folded
Toffoli/CNOT/X circuit witness, with public bounds obtained from the matching
component-resource certificate [PZ03, ecc.tex:144-188, 448-462] [Sho95,
source.tex:1704-1784] [RNSL17, ECDLP.tex:129-194]. -/
theorem main_sameCircuit_exactResource_of_fourier_sampling_support
    {p : Nat} {E : PrimeFieldShortWeierstrass p} [Fact p.Prime]
    {I : ECDLPInstance E}
    {G : Type u} [Group G]
    {P : QuantumAlg.FiniteCyclicDLP.KnownOrderProblem G} {Ω : Type v}
    (support : QuantumAlg.FiniteCyclicDLP.FourierSamplingSupport P Ω)
    (bridge : FiniteCyclicBridge I P support.secret)
    (scalarOracle : SameCircuitScalarOracleCertificate E)
    (params : QuantumAlg.FiniteCyclicDLP.ResourceParameters)
    (bounds : QuantumAlg.FiniteCyclicDLP.PublicBaselineBounds.FormulaParameters)
    (hgroupFromScalar :
      params.groupRegisterQubits = scalarOracle.profile.logicalQubits)
    (horacleDepthFromScalar :
      params.oracleDepth = scalarOracle.profile.circuitDepth)
    (horderBits : params.orderRegisterQubits ≤ bounds.orderBitUpperBound)
    (hgroup : params.groupRegisterQubits ≤ bounds.groupRegisterQubitBound)
    (horacleDepth : params.oracleDepth ≤ bounds.oracleDepthBound)
    (hfourierDepth : params.fourierLayerDepth ≤ bounds.fourierLayerDepthBound)
    (hclassical :
      params.classicalPostProcessing.total ≤ bounds.classicalOperationBound) :
    let sampling : QuantumAlg.FiniteCyclicDLP.SamplingCertificate P Ω :=
      support.toSamplingCertificate
    (∀ outcome (hgood : outcome ∈ sampling.goodEvents),
      I.CandidateScalar
        (bridge.toECDLPScalar ((sampling.recovery outcome hgood).output))) ∧
      sampling.SuccessAtLeastTwoThirds ∧
      (2 : ℝ) / 3 ≤ sampling.goodMass ∧
      (sampling.successNumerator : ℝ) /
          (sampling.successDenominator : ℝ) ≤ sampling.goodMass ∧
      0 ≤ sampling.goodMass ∧
      sampling.goodMass ≤ 1 ∧
      QuantumAlg.FiniteCyclicDLP.ExactResourceProfile.HasExactCounts
        params.toExactResourceProfile
        1
        (2 * params.orderRegisterQubits + scalarOracle.profile.logicalQubits)
        (2 * params.orderRegisterQubits)
        (params.orderRegisterQubits * (params.orderRegisterQubits - 1))
        (2 * (params.orderRegisterQubits / 2))
        (scalarOracle.profile.circuitDepth + params.fourierLayerDepth)
        params.classicalPostProcessing.total ∧
      QuantumAlg.FiniteCyclicDLP.SupportsPublicBaseline
        params.toExactResourceProfile bounds.toPublicBaselineBounds ∧
      scalarOracle.resourceCorrectWitness.circuit = scalarOracle.circuit ∧
      scalarOracle.circuit.history.IsBaseGateStructured ∧
      SameCircuitResourceFields.ExactForProfile
        scalarOracle.resourceFields scalarOracle.profile ∧
      scalarOracle.circuit.resources =
        scalarOracle.profile.toResourceProfile ∧
      scalarOracle.circuit.depth = scalarOracle.profile.circuitDepth ∧
      scalarOracle.circuit.queryDepth = scalarOracle.profile.oracleQueries ∧
      ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
        scalarOracle.schedule scalarOracle.profile scalarOracle.bounds ∧
      ModularArithmeticResourceProfile.SupportsUpperBound
        scalarOracle.profile scalarOracle.boundProfile := by
  dsimp
  rcases
    main_with_public_bounds_of_fourier_sampling_support
      support bridge scalarOracle.toResourceCertificate params bounds
      horderBits hgroup horacleDepth hfourierDepth hclassical with
    ⟨hrecover, hsuccess, htwoThirds, hrational, hnonneg, hleOne, hexact,
      hsupports, _hscalarSupports, _hscalarUpper⟩
  have hexactSameCircuit :
      QuantumAlg.FiniteCyclicDLP.ExactResourceProfile.HasExactCounts
        params.toExactResourceProfile
        1
        (2 * params.orderRegisterQubits + scalarOracle.profile.logicalQubits)
        (2 * params.orderRegisterQubits)
        (params.orderRegisterQubits * (params.orderRegisterQubits - 1))
        (2 * (params.orderRegisterQubits / 2))
        (scalarOracle.profile.circuitDepth + params.fourierLayerDepth)
        params.classicalPostProcessing.total := by
    rw [← hgroupFromScalar, ← horacleDepthFromScalar]
    exact hexact
  exact
    ⟨hrecover, hsuccess, htwoThirds, hrational, hnonneg, hleOne,
      hexactSameCircuit, hsupports, scalarOracle.resourceCorrectWitness_circuit,
      scalarOracle.structured, scalarOracle.resourceFields_exact,
      scalarOracle.resources_eq, scalarOracle.depth_eq,
      scalarOracle.queryDepth_eq, scalarOracle.supportsPublicBaseline,
      scalarOracle.supportsUpperBound⟩

/-- Eta-amplified ECDLP scalar-recovery endpoint from finite-cyclic
Fourier-sampling support.  The theorem preserves the one-run `>= 2/3`
finite-cyclic success certificate, and adds a separate eta certificate that
records the repeated-run failure bound and the retry upper-bound parameter
[Sho95, source.tex:1924-1987]. -/
theorem main_with_eta_amplification_of_fourier_sampling_support
    {p : Nat} {E : PrimeFieldShortWeierstrass p} {I : ECDLPInstance E}
    {G : Type u} [Group G]
    {P : QuantumAlg.FiniteCyclicDLP.KnownOrderProblem G} {Ω : Type v}
    (support : QuantumAlg.FiniteCyclicDLP.FourierSamplingSupport P Ω)
    (bridge : FiniteCyclicBridge I P support.secret)
    (scalarOracle : ScalarOracleResourceCertificate E)
    (params : QuantumAlg.FiniteCyclicDLP.ResourceParameters)
    (bounds : QuantumAlg.FiniteCyclicDLP.PublicBaselineBounds.FormulaParameters)
    (eta : Factoring.FailureBudget)
    (amplification : SuccessAmplification.EtaCertificate eta)
    (horderBits : params.orderRegisterQubits ≤ bounds.orderBitUpperBound)
    (hgroup : params.groupRegisterQubits ≤ bounds.groupRegisterQubitBound)
    (horacleDepth : params.oracleDepth ≤ bounds.oracleDepthBound)
    (hfourierDepth : params.fourierLayerDepth ≤ bounds.fourierLayerDepthBound)
    (hclassical :
      params.classicalPostProcessing.total ≤ bounds.classicalOperationBound) :
    let sampling : QuantumAlg.FiniteCyclicDLP.SamplingCertificate P Ω :=
      support.toSamplingCertificate
    (∀ outcome (hgood : outcome ∈ sampling.goodEvents),
      I.CandidateScalar
        (bridge.toECDLPScalar ((sampling.recovery outcome hgood).output))) ∧
      sampling.SuccessAtLeastTwoThirds ∧
      (2 : ℝ) / 3 ≤ sampling.goodMass ∧
      (sampling.successNumerator : ℝ) /
          (sampling.successDenominator : ℝ) ≤ sampling.goodMass ∧
      0 ≤ sampling.goodMass ∧
      sampling.goodMass ≤ 1 ∧
      eta.WellFormed ∧
      amplification.repetitionModel.failureNumerator * eta.failureDenominator ≤
        eta.failureNumerator * amplification.repetitionModel.failureDenominator ∧
      amplification.retrySpec.readyForFinalStatement = true ∧
      amplification.retrySpec.runCount ≤ amplification.logInvEtaUpperBound ∧
      QuantumAlg.FiniteCyclicDLP.ExactResourceProfile.HasExactCounts
        params.toExactResourceProfile
        1
        (2 * params.orderRegisterQubits + params.groupRegisterQubits)
        (2 * params.orderRegisterQubits)
        (params.orderRegisterQubits * (params.orderRegisterQubits - 1))
        (2 * (params.orderRegisterQubits / 2))
        (params.oracleDepth + params.fourierLayerDepth)
        params.classicalPostProcessing.total ∧
      QuantumAlg.FiniteCyclicDLP.SupportsPublicBaseline
        params.toExactResourceProfile bounds.toPublicBaselineBounds ∧
      ScalarMultiplication.CertifiedEndpoint.ResourceParameters.SupportsPublicBaseline
        scalarOracle.schedule scalarOracle.profile scalarOracle.bounds ∧
      ModularArithmeticResourceProfile.SupportsUpperBound
        scalarOracle.profile scalarOracle.boundProfile := by
  dsimp
  rcases
    main_with_public_bounds_of_fourier_sampling_support
      support bridge scalarOracle params bounds horderBits hgroup horacleDepth
      hfourierDepth hclassical with
    ⟨hrecover, hsuccess, htwoThirds, hrational, hnonneg, hleOne, hexact,
      hsupports, hscalarSupports, hscalarUpper⟩
  refine
    ⟨hrecover, hsuccess, htwoThirds, hrational, hnonneg, hleOne,
      amplification.eta_wellFormed, ?_, ?_, ?_, hexact, hsupports,
      hscalarSupports, hscalarUpper⟩
  · exact
      SuccessAmplification.EtaCertificate.repeatedFailure_le_eta amplification
  · exact
      SuccessAmplification.EtaCertificate.retrySpec_ready amplification
  · simpa [SuccessAmplification.EtaCertificate.retrySpec,
      SuccessAmplification.etaRetrySpec] using
      amplification.runCount_le_logInvEtaUpperBound

end ECDLP
end PrimeFieldShortWeierstrass
end EllipticCurve
end QuantumAlg
