/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import QuantumAlg.Init
public import QuantumAlg.Core.Base
public import Mathlib.Algebra.Lie.OfAssociative
public import Mathlib.Algebra.Lie.Subalgebra
public import Mathlib.LinearAlgebra.Complex.FiniteDimensional
public import Mathlib.LinearAlgebra.Matrix.ConjTranspose
public import Mathlib.LinearAlgebra.Matrix.FiniteDimensional

/-!
# The dynamical Lie algebra

The **dynamical Lie algebra** (DLA) of a parameterized quantum circuit with
generators `{H₁, …, H_K}` is the Lie closure `g = ⟨i H₁, …, i H_K⟩_Lie` — the
smallest Lie subalgebra (under the matrix commutator `⁅A, B⁆ = A B − B A`)
containing the (skew-Hermitian) generators. Its dimension governs circuit
expressibility, overparametrization, and barren-plateau trainability.

Here the ambient Lie algebra is `gl(N, ℂ) = Matrix (Fin N) (Fin N) ℂ` with its
commutator bracket (`LieAlgebra.ofAssociativeAlgebra`). The DLA is defined for an
arbitrary set of matrix generators via `LieSubalgebra.lieSpan`. The physical
generators `i • Hₖ` are skew-Hermitian; because `lieSpan` closes over the complex
scalars `ℂ`, the resulting algebra is the **complexification** `g_ℂ` of a real Lie
algebra `g ⊆ u(N)` — it is *not* itself contained in `u(N)` (it contains the
Hermitian `Hₖ = -i • (i • Hₖ)`). For skew-Hermitian generators `g_ℂ` is closed
under the adjoint `star` (`dynamicalLieAlgebra_star_mem`), and its Hermitian real
form `dlaRealForm` has real dimension equal to the complex dimension `dim_ℂ g_ℂ`
(`finrank_real_realForm_eq_finrank_complex_dla`) — the identification used by `dlaDim`.

Sources: [RBS+23, Arxiv_Final.tex:636-638] (DLA defined as the Lie closure
`g = ⟨i𝒢⟩_Lie` of the circuit generators); [ASY+24, Quantum-main.tex:58]
(DLAs of parameterized circuits as expressiveness/trainability invariants).

## Main definitions / results

- `QuantumAlg.dynamicalLieAlgebra` — the Lie subalgebra generated by the
  generator set (the Lie closure).
- `QuantumAlg.generators_subset_dynamicalLieAlgebra` — the generators lie in it.
- `QuantumAlg.dynamicalLieAlgebra_le_iff` / `dynamicalLieAlgebra_minimal` — its
  universal property: it is the smallest Lie subalgebra containing the generators.
- `QuantumAlg.dynamicalLieAlgebra_star_mem` — for skew-Hermitian generators the DLA
  is closed under the adjoint `star` (it is the complexification of a real form).
- `QuantumAlg.dlaRealForm` / `QuantumAlg.finrank_real_realForm_eq_finrank_complex_dla`
  — the Hermitian real form `g_ℂ ∩ {Xᴴ = X}` and the dimension bridge
  `dim_ℝ (dlaRealForm) = dim_ℂ g_ℂ`.
-/

@[expose] public section

namespace QuantumAlg

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable {N : ℕ}

/-- The dynamical Lie algebra generated by a set of matrix generators: the
smallest Lie subalgebra of `gl(N, ℂ)` (with the commutator bracket) containing
them — the Lie closure under nested commutators. -/
def dynamicalLieAlgebra (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ) :=
  LieSubalgebra.lieSpan ℂ (Matrix (Fin N) (Fin N) ℂ) gens

/-- The generators belong to their dynamical Lie algebra. -/
theorem generators_subset_dynamicalLieAlgebra
    (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.subset_lieSpan

/-- **Universal property.** The dynamical Lie algebra is contained in a Lie
subalgebra `K` exactly when all generators are. -/
theorem dynamicalLieAlgebra_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.lieSpan_le

/-- **Minimality.** The dynamical Lie algebra is the smallest Lie subalgebra
containing the generators. -/
theorem dynamicalLieAlgebra_minimal (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  LieSubalgebra.lieSpan_le.mpr h

/-! ### `*`-closure and the Hermitian real form of the DLA -/

/-- **The dynamical Lie algebra of skew-Hermitian generators is `*`-closed.** If every
generator `A` is skew-Hermitian (`star A = -A`, the physical case `A = i H` with `H`
Hermitian), then the adjoint `star x = xᴴ` of any element of the dynamical Lie algebra
is again in it. Hence the DLA is the complexification of a real Lie algebra inside
`u(N)`, and admits a Hilbert–Schmidt orthonormal basis of Hermitian matrices. -/
theorem dynamicalLieAlgebra_star_mem
    {gens : Set (Matrix (Fin N) (Fin N) ℂ)} (hskew : ∀ A ∈ gens, star A = -A)
    {x : Matrix (Fin N) (Fin N) ℂ} (hx : x ∈ dynamicalLieAlgebra gens) :
    star x ∈ dynamicalLieAlgebra gens := by
  refine LieSubalgebra.lieSpan_induction ℂ
    (p := fun t _ => star t ∈ dynamicalLieAlgebra gens) ?_ ?_ ?_ ?_ ?_ hx
  · -- generators: `star b = -b ∈ DLA`
    intro b hb
    simpa only [dynamicalLieAlgebra, hskew b hb] using
      neg_mem (LieSubalgebra.subset_lieSpan hb)
  · -- zero
    simp
  · -- addition
    intro a b _ _ ha hb
    simpa only [star_add] using add_mem ha hb
  · -- scalar multiplication
    intro c a _ ha
    simpa only [star_smul] using SMulMemClass.smul_mem (star c) ha
  · -- Lie bracket: `star ⁅a,b⁆ = -⁅star a, star b⁆ ∈ DLA`
    intro a b _ _ ha hb
    have h : star ⁅a, b⁆ = -⁅star a, star b⁆ := by
      simp only [Ring.lie_def, star_sub, star_mul]
      abel
    simpa only [h] using neg_mem (LieSubalgebra.lie_mem _ ha hb)

open Matrix in
/-- Restated with the conjugate-transpose notation: the DLA of skew-Hermitian
generators is closed under `(·)ᴴ`. -/
theorem dynamicalLieAlgebra_conjTranspose_mem
    {gens : Set (Matrix (Fin N) (Fin N) ℂ)} (hskew : ∀ A ∈ gens, Aᴴ = -A)
    {x : Matrix (Fin N) (Fin N) ℂ} (hx : x ∈ dynamicalLieAlgebra gens) :
    xᴴ ∈ dynamicalLieAlgebra gens := by
  have := dynamicalLieAlgebra_star_mem (gens := gens)
    (by simpa only [star_eq_conjTranspose] using hskew) hx
  simpa only [star_eq_conjTranspose] using this

open Complex in
/-- **Real-form dimension bridge.** A finite-dimensional complex subspace `W` (of a
complex `*`-module `M`) that is closed under `star` decomposes real-linearly as
`V_h ⊕ i • V_h` over its self-adjoint part `V_h = {x ∈ W | star x = x}`; hence the real
dimension of `V_h` equals the complex dimension of `W`. Concretely `x ↦ (ℜ x, ℑ x)` is an
`ℝ`-linear isomorphism `W ≃ V_h × V_h`, so `dim_ℝ W = 2 · dim_ℝ V_h`, while
`dim_ℝ W = 2 · dim_ℂ W` (`finrank_real_of_complex`). -/
theorem finrank_selfAdjoint_inf_restrictScalars_eq
    {M : Type*} [AddCommGroup M] [Module ℂ M] [StarAddMonoid M] [StarModule ℂ M]
    [FiniteDimensional ℂ M] (W : Submodule ℂ M) (hW : ∀ x ∈ W, star x ∈ W) :
    Module.finrank ℝ ↥(selfAdjoint.submodule ℝ M ⊓ W.restrictScalars ℝ)
      = Module.finrank ℂ W := by
  set Vh : Submodule ℝ M := selfAdjoint.submodule ℝ M ⊓ W.restrictScalars ℝ with hVhdef
  have hle1 : Vh ≤ selfAdjoint.submodule ℝ M := by rw [hVhdef]; exact inf_le_left
  have hle2 : Vh ≤ W.restrictScalars ℝ := by rw [hVhdef]; exact inf_le_right
  have hself : ∀ x : Vh, IsSelfAdjoint (x : M) := fun x => hle1 x.2
  have hinW : ∀ x : Vh, (x : M) ∈ W := fun x => hle2 x.2
  have hmemR : ∀ {w : M}, w ∈ W → (realPart w : M) ∈ Vh := by
    intro w hw
    rw [hVhdef, Submodule.mem_inf]
    refine ⟨(realPart w).2, ?_⟩
    rw [Submodule.restrictScalars_mem, realPart_apply_coe]
    exact W.smul_of_tower_mem _ (add_mem hw (hW w hw))
  have hmemI : ∀ {w : M}, w ∈ W → (imaginaryPart w : M) ∈ Vh := by
    intro w hw
    rw [hVhdef, Submodule.mem_inf]
    refine ⟨(imaginaryPart w).2, ?_⟩
    rw [Submodule.restrictScalars_mem, imaginaryPart_apply_coe]
    exact W.smul_mem _ (W.smul_of_tower_mem _ (sub_mem hw (hW w hw)))
  let reM : M →ₗ[ℝ] M := (selfAdjoint.submodule ℝ M).subtype ∘ₗ realPart
  let imM : M →ₗ[ℝ] M := (selfAdjoint.submodule ℝ M).subtype ∘ₗ imaginaryPart
  let fR : (W.restrictScalars ℝ) →ₗ[ℝ] Vh :=
    LinearMap.codRestrict Vh (reM ∘ₗ (W.restrictScalars ℝ).subtype) (fun w => hmemR w.2)
  let fI : (W.restrictScalars ℝ) →ₗ[ℝ] Vh :=
    LinearMap.codRestrict Vh (imM ∘ₗ (W.restrictScalars ℝ).subtype) (fun w => hmemI w.2)
  let toLin : (W.restrictScalars ℝ) →ₗ[ℝ] (Vh × Vh) := fR.prod fI
  let Ismul : M →ₗ[ℝ] M := (LinearMap.lsmul ℂ M I).restrictScalars ℝ
  let gRaw : (Vh × Vh) →ₗ[ℝ] M :=
    Vh.subtype ∘ₗ (LinearMap.fst ℝ Vh Vh) + (Ismul ∘ₗ Vh.subtype) ∘ₗ (LinearMap.snd ℝ Vh Vh)
  have hgmem : ∀ p : Vh × Vh, gRaw p ∈ W.restrictScalars ℝ := by
    intro p
    change (p.1 : M) + I • (p.2 : M) ∈ W.restrictScalars ℝ
    rw [Submodule.restrictScalars_mem]
    exact add_mem (hinW p.1) (W.smul_mem _ (hinW p.2))
  let g : (Vh × Vh) →ₗ[ℝ] (W.restrictScalars ℝ) :=
    LinearMap.codRestrict (W.restrictScalars ℝ) gRaw hgmem
  let e : (W.restrictScalars ℝ) ≃ₗ[ℝ] (Vh × Vh) :=
    LinearEquiv.ofLinear toLin g
      (by
        refine LinearMap.ext fun p => ?_
        have hsa : IsSelfAdjoint (p.1 : M) := hself p.1
        have hsb : IsSelfAdjoint (p.2 : M) := hself p.2
        refine Prod.ext ?_ ?_
        · apply Subtype.ext
          change (realPart ((p.1 : M) + I • (p.2 : M)) : M) = (p.1 : M)
          rw [map_add, realPart_I_smul]
          simp [hsa.coe_realPart, hsb.imaginaryPart]
        · apply Subtype.ext
          change (imaginaryPart ((p.1 : M) + I • (p.2 : M)) : M) = (p.2 : M)
          rw [map_add, imaginaryPart_I_smul]
          simp [hsb.coe_realPart, hsa.imaginaryPart])
      (by
        refine LinearMap.ext fun w => ?_
        apply Subtype.ext
        change (realPart (w : M) : M) + I • (imaginaryPart (w : M) : M) = (w : M)
        exact realPart_add_I_smul_imaginaryPart (w : M))
  have hprod : Module.finrank ℝ Vh + Module.finrank ℝ Vh
      = Module.finrank ℝ (W.restrictScalars ℝ) := by
    rw [← Module.finrank_prod, ← e.finrank_eq]
  have hcx : Module.finrank ℝ (W.restrictScalars ℝ) = 2 * Module.finrank ℂ W :=
    finrank_real_of_complex (W : Type _)
  omega

/-- The **Hermitian real form** of the dynamical Lie algebra: `V_h = g_ℂ ∩ {X | Xᴴ = X}`,
the self-adjoint elements of the DLA, as an `ℝ`-subspace of `gl(N, ℂ)`. For skew-Hermitian
generators `V_h = i • g` where `g ⊆ u(N)` is the skew-Hermitian real Lie algebra whose
complexification is the DLA; the two have the same real dimension. -/
def dlaRealForm (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    Submodule ℝ (Matrix (Fin N) (Fin N) ℂ) :=
  selfAdjoint.submodule ℝ (Matrix (Fin N) (Fin N) ℂ)
    ⊓ (dynamicalLieAlgebra gens).toSubmodule.restrictScalars ℝ

/-- **Real-form dimension bridge for the DLA.** For skew-Hermitian generators the DLA
`g_ℂ = dynamicalLieAlgebra gens` is `*`-closed (`dynamicalLieAlgebra_star_mem`), so its
Hermitian real form `dlaRealForm gens` satisfies `dim_ℝ (dlaRealForm gens) = dim_ℂ g_ℂ`.
This is the identity `dim_ℝ g = dim_ℂ g_ℂ` that makes `dlaDim` (the `ℂ`-finrank of the DLA)
equal the literature real dimension. -/
theorem finrank_real_realForm_eq_finrank_complex_dla
    {gens : Set (Matrix (Fin N) (Fin N) ℂ)} (hskew : ∀ A ∈ gens, star A = -A) :
    Module.finrank ℝ (dlaRealForm gens)
      = Module.finrank ℂ (dynamicalLieAlgebra gens).toSubmodule :=
  finrank_selfAdjoint_inf_restrictScalars_eq (dynamicalLieAlgebra gens).toSubmodule
    (fun _ hx => dynamicalLieAlgebra_star_mem hskew hx)

namespace DynamicalLieAlgebra

/-- Main theorem: the DLA is the smallest Lie subalgebra containing the generators. -/
theorem main (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  dynamicalLieAlgebra_minimal gens h

/-- Public supporting theorem: generators belong to their DLA. -/
theorem main_generators_subset (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  generators_subset_dynamicalLieAlgebra gens

/-- Public supporting theorem: the universal property of the DLA. -/
theorem main_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  dynamicalLieAlgebra_le_iff gens K

end DynamicalLieAlgebra

end

end QuantumAlg
